### ISSUE TITLE
Filter intelliSense completion for `@` character to only show attributes

### ISSUE THREAD

**Issue by cgranade** [microsoft/qsharp-compiler#1005]
**Is your feature request related to a problem? Please describe.**
When typing the `@` character before a declaration, intelliSense currently suggests a number of unrelated completions. For example, typing `@T` suggests `T`, `Tail`, and many other callables that cannot be used as attributes.

![image](https://user-images.githubusercontent.com/31516/116472268-8649ac00-a82a-11eb-963b-0204adc34909.png)

**Describe the solution you'd like**
It would be helpful if in this case, only attributes such as `@Test` were suggested as possible completions.

**Comment by filipw** [comment]
this looks like a duplicate of https://github.com/microsoft/qsharp-compiler/issues/659

**Comment by cgranade** [comment]
Ah, so it is! Not sure why that didn't show up in searching, but will go on and close this one, then. Thanks!
