### ISSUE TITLE
QIR: Use of hard-coded strings in if-statement can result in variable use outside of scope

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-compiler#1018]
When compiling a conditional that uses hard-coded strings in an if-statement, the resulting QIR can include use of the variable outside of the scope it was defined in, specifically for the reference counting to free the string. If this small program is compiled:
```qsharp
    @EntryPoint()
    operation Test(input : String) : Unit {
        if input == "true" {
            let _ = true;
        } elif input == "false" {
            let _ = false;
        }
    }
```
then it will result in this QIR:
```llvm
define internal void @Microsoft__Quantum__Qir__Emission__Test__body(%String* %input) {
entry:
  %0 = call %String* @__quantum__rt__string_create(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @0, i32 0, i32 0))
  %1 = call i1 @__quantum__rt__string_equal(%String* %input, %String* %0)
  br i1 %1, label %then0__1, label %test1__1

then0__1:                                         ; preds = %entry
  br label %continue__1

test1__1:                                         ; preds = %entry
  %2 = call %String* @__quantum__rt__string_create(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @1, i32 0, i32 0))
  %3 = call i1 @__quantum__rt__string_equal(%String* %input, %String* %2)
  br i1 %3, label %then1__1, label %continue__1

then1__1:                                         ; preds = %test1__1
  br label %continue__1

continue__1:                                      ; preds = %then1__1, %test1__1, %then0__1
  call void @__quantum__rt__string_update_reference_count(%String* %0, i32 -1)
  call void @__quantum__rt__string_update_reference_count(%String* %2, i32 -1)
  ret void
}
```
where `@0` is the hard-coded "true" and `@1` is the hard-coded "false". Note that the `continue__1` block includes the logic for decrementing the ref count on both strings that were loaded from hard-coded values, `%0` and `%2`, but because `%2` is created in the `test1_1` block corresponding to the `elif` in the source code, it might not enter that block if the string did equal "true", so an input of "true" would cause this code to crash. Clang recognizes this and fails to compile with the error "Instruction does not dominate all uses!"

**Comment by bettinaheim** [comment]
Ow wow, I know exactly what the issue is (the branching is formally only started after the condition evaluation...), but I would not have been able to come up with that case without running into it!
