### ISSUE TITLE
Language server failed

### ISSUE THREAD

**Issue by kuzminrobin** [microsoft/qsharp-compiler#1020]
I have **qsharp-runtime** repo open in VS Code.
I open **QuantumLibraries** repo in another instance of VS Code (with command `code .`) and VS Code shows a notification in the bottom-right corner:
> Language server failed to start: Error: EBUSY: resource busy or locked, rmdir 'c:\Users\rokuzmin\AppData\Roaming\Code\User\globalStorage\quantum.quantum-devkit-vscode\server'

When I dismiss that notification, it sends me to here, to open this bug.
100% repro (4 of 4). See screenshot below.

![image](https://user-images.githubusercontent.com/9372582/117371372-9e4dab00-ae7c-11eb-9cf4-b3746894f0ee.png)

**Comment by bettinaheim** [comment]
I'll close this as I couldn't repro this, and given the message, it seemed likely that this was a transient issue due to a locked resource that is outside our control. Please reopen it if reoccurs.
