### ISSUE TITLE
Error cannot run the hello world template  

### ISSUE THREAD

**Issue by ChairmanPandaCN** [microsoft/qsharp-compiler#1023]
**Describe the bug**

1.Cannot run the hello world application due to dotnet run error
![image](https://user-images.githubusercontent.com/32951648/117609700-5ff40c80-b158-11eb-9364-9eb560182fd4.png)

Dotnet reinstallation doesn't fix this problem.

**How To Reproduce**

1. dotnet new console -lang Q# -o runSayHello
2. cd runSayHello
3. dotnet run

**More Info**
Laptop Info :
![image](https://user-images.githubusercontent.com/32951648/117609954-d4c74680-b158-11eb-8e2f-d5b7332413cd.png)

Method of installing .Net :
 1. yay -S dotnet-sdk dotnet-runtime

**Expected behavior**

Expecting "Hello quantum world!" in console.

**Comment by ChairmanPandaCN** [comment]
![image](https://user-images.githubusercontent.com/32951648/117610439-ab5aea80-b159-11eb-82fc-23f2db5f2e98.png)
QDK for vscode was installed manually instead of using the command,ext install quantum.quantum-devkit-vscode, as it doesn't work.

**Comment by bettinaheim** [comment]
This is an odd one. Could you check if you can create a file in the output location that the command lists, i.e. from that folder, can you run `touch obj/qsharp/config/qsc.config`, and do you see the created file in that location afterwards? What shell/terminal/command prompt are you using?

**Comment by bettinaheim** [comment]
@ChairmanPandaCN Could it be that you have only .NET 5 installed, and not 3.1? If so, I believe that may cause the issue. 
Here is the issue for supporting .NET 5: https://github.com/microsoft/qsharp-compiler/issues/977.
Could you confirm if [installing .NET 3.1](https://dotnet.microsoft.com/download/dotnet/3.1) fixes the issue?

**Comment by ChairmanPandaCN** [comment]
Switch from dotnet 5 to dotnet 3.1 did fix the problem....
