### ISSUE TITLE
Q# empty string becomes null in QIR, causing segmentation faults in runtime

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-compiler#1043]
An empty string in Q# today seems to generate into an explicit null in QIR rather than remaining an empty string. For example, the code:
```qsharp
Message("");
```
becomes:
```llvm
  %0 = call %String* @__quantum__rt__string_create(i8* null)
  call void @__quantum__rt__message(%String* %0)
  call void @__quantum__rt__string_update_reference_count(%String* %0, i32 -1)
```
This code will cause a segmentation fault in the runtime when the null goes through string creation, as it eventually gets passed into the constructor for `std::string`.

It seems to me that since Q# works hard to not have null in the language, this should get generated into an empty string literal (ie: `internal constant [1 x i8] c"\00"`) rather than an explicit null. Looking at the [QIR spec for strings](https://github.com/microsoft/qsharp-language/blob/main/Specifications/QIR/Data-Types.md#strings), it does say that the input to `__quantum__rt__string_create` is expected to be a null terminated byte array, which implies that it cannot be null. It might be worth calling out that null is not supported as input.

**Comment by bettinaheim** [comment]
Digging a bit about whether we can avoid passing a null pointer for empty strings, the issue that I haven't found my way around yet is that LLVM.ConstStringInContext returns a zero-initializer when the string to construct is empty.
Possibly related: https://reviews.llvm.org/D24904

**Comment by bettinaheim** [comment]
Alright, here is the PR: https://github.com/microsoft/qsharp-compiler/pull/1073
It's not pretty but it's the best I can come up with to work around this.
