### ISSUE TITLE
Looping n-qubits = loop X n-qubit = InsufficientResource: Is this by design?

### ISSUE THREAD

**Issue by giobb** [microsoft/qsharp-compiler#1053]
The routine below produces **InsufficientResource** error on the IonQ 11-qubit QPU. I found out that in the **translatedInputData.json** 24 qubits are allocated instead of just 3 at a time therefore exhausting all qubits (3-iteration obviously works) . What is the purpose of _**using...... ResetAll**_ here then? Is there a correct way of achieving this?

![Loop code](https://user-images.githubusercontent.com/15137038/120426609-455f1e80-c325-11eb-915e-bbec7ae33287.png)
![too many qubit requested](https://user-images.githubusercontent.com/15137038/120427504-dedb0000-c326-11eb-8b87-9efc8c5f40ac.png)

Here are the job files
[quantum-job-d15f8d16-e5cd-4a2c-b69c-a39c26ea11b8 - simulator.zip](https://github.com/microsoft/qsharp-compiler/files/6582100/quantum-job-d15f8d16-e5cd-4a2c-b69c-a39c26ea11b8.-.simulator.zip)
[quantum-job-adf7ca87-9d76-4628-9bab-ef0964c24181 - qpu.zip](https://github.com/microsoft/qsharp-compiler/files/6582101/quantum-job-adf7ca87-9d76-4628-9bab-ef0964c24181.-.qpu.zip)

I'm using QDK ver **0.17.2105143879**. You may also refer to the file in my [repo](https://github.com/giobb/quantum-computing-demo/blob/debuggin-loop/DJ/DJQS/Program.qs).

**Comment by swernli** [comment]
This is actually expected behavior for the IonQ system. The IonQ hardware does not allow for qubit reuse, so once a qubit is measured it cannot be used again later in execution. As a result, the code sample you provided will need to allocate 3 fresh qubits through each iteration of the loop, adding up to the total of 24 qubits as you observed.

**Comment by giobb** [comment]
Thanks @swernli  for clarifying. You just saved me hours of investigation.
![Honeywells output](https://user-images.githubusercontent.com/15137038/120590248-16ad7a80-c3ef-11eb-9eb2-4175ada4a0d4.png)


I notice that Honeywell doesn't have this issue. However, I found out something odd. The result for the job below is always **all zero's** for Honewell's  _**honeywell.hqs-lt-1.0-apival**_ but they come **correct with IonQ.** I first noticed this when I run my DJ program - HW gives 0's for all the functions! Is there some coding considerations again with HW like that of IonQ's inability to reset? It seems like all the initial values in my array were never touched.

![Looping qubit nx](https://user-images.githubusercontent.com/15137038/120590003-a6065e00-c3ee-11eb-8879-cf28bef83a96.png)

Sample output of Honeywell
![Honeywells output](https://user-images.githubusercontent.com/15137038/120590274-2036e280-c3ef-11eb-9381-528ff1c73687.png)

**Comment by swernli** [comment]
Happy to help, @giobb! For the Honeywell apival target, this is similarly expected and a common point of confusion. Currently, Honeywell does not offer a simulator target, and the apival targets they expose only perform basic validation of the input program without any simulation. As a result, they will return all zeros for every qubit on a successful validation and a failure message if any incompatible inputs are provided.

**Comment by giobb** [comment]
Thanks @swernli. Is the apival a simulator? So essentially what HW just achieved for me is validate my input and not even attempt to run what's inside the iteration. How do I submit such logic then for HW?

**Comment by swernli** [comment]
Honeywell exposes two targets, honeywell.hqs-lt-1.0 and honeywell.hqs-lt-1.0-apival. The "-apival" suffix identifies that one as purely an API Validator, so it is neither hardware nor a simulator (basically the equivalent of a spell checker). If you want to actually submit for execution on hardware, use the honeywell.hqs-lt-1.0 target instead.

**Comment by giobb** [comment]
Hi swernli, any idea why the block above actually took 15hrs to finish? I checked the spec again and it seems like I'm just hitting against a 6-Qbit machine.  I'm still trying to reach HW support. I don't want any surprise later in my bill 
![Honeywell 15-hr run](https://user-images.githubusercontent.com/15137038/120836061-00e8a400-c51a-11eb-8129-6b88ffc523cc.jpg)

**Comment by swernli** [comment]
@giobb, that is definitely surprising and shouldn't have been that long. It's possible this is a bug in the reporting for queued time vs execution time. Could you try querying the JSON for the job using az CLI, ie: `az quantum job show -j <JOB_ID>` ? In particular, I'm interested in the fields `creationTime`, `beginExecutionTime`, and `endExecutionTime`.

**Comment by giobb** [comment]
@swernli times are so close so it must be a bug. The 500 though in the input scares me. What's that?  :)

![HW QC Job details](https://user-images.githubusercontent.com/15137038/120843619-2e861b00-c523-11eb-95df-8cf540262ab6.png)

**Comment by swernli** [comment]
@giobb This job ran against the API Validator, not hardware (`"target": "honeywell.hqs-lt-1.0-apival"`) which is why the turn around time was so fast. You'll need to use the job ID for the one that was submitted to `honeywell.hqs-lt-1.0` for us to double check hardware execution times.

The 500 in the input params under "count" is how Honeywell receives the number of shots, and 500 is the Azure Quantum default shot count when no explicit shot count is specified.

**Comment by giobb** [comment]
Oops my bad.
![HW QC Job details real](https://user-images.githubusercontent.com/15137038/120855468-5da48880-c533-11eb-984e-f06c86312f03.png)

**Comment by swernli** [comment]
Fascinating... it does indeed appear that the job was in the queue for about 4.5 hours, and then "executing" for over 15 hours. I highly doubt that 500 shots of the algorithm you've shown above would take 15 hours to execute, so this definitely something that is worth following up with Honeywell about. I can start that conversation on my end, but it would good for you to send an email to Honeywell Azure Quantum support at HoneywellAzureQuantumSupport@Honeywell.com (see [here](https://docs.microsoft.com/en-us/azure/quantum/provider-support-honeywell) for more details on support).

**Comment by swernli** [comment]
Also, it would be worth removing or trimming the screenshots you provided, as the "inputDataUri" and "outputDataUri" fields include addresses with embedded access credentials. Apologies for not warning about that sooner!

**Comment by giobb** [comment]
Thanks again! Will reach out accordingly,
