### ISSUE TITLE
Improve error message for implicitly ignored result

### ISSUE THREAD

**Issue by troelsfr** [microsoft/qsharp-compiler#1094]
**Describe the improvement**

The Q# compiler gives slightly unhelpful error messages when calling non-`Unit` without explicitly ignoring the result. Whenever a call is made without explicitly ignoring the result, the compiler should suggest to either use `Ignore( ... )` or change the return type of the function to `Unit`. At the moment, it only does the latter.

**To Reproduce**

To reproduce, compile following to programs:

```
namespace Example {
@EntryPoint()
operation Main() : Int
{
QuantumFunction(3);
return QuantumFunction(10);
}

operation QuantumFunction(nQubits : Int) : Int {
use qubits = Qubit[nQubits];

return 0;
}
}
```
does not compile and has following output
```
% dotnet build ConstSizeArray.csproj
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

Determining projects to restore...
All projects are up-to-date for restore.
Determining projects to restore...
All projects are up-to-date for restore.
ConstSizeArray.qs(8,9): error QS0001: The type Int does not match the type Unit. [ConstSizeArray/ConstSizeArray.csproj]
Actual type: Int
Expected type: Unit

____________________________________________

Q# compilation failed: 1 error, 0 warnings

(...)
```

**Expected behavior**

```
ConstSizeArray.qs(8,9): error QS0001: Return value implicitly ignored. [ConstSizeArray/ConstSizeArray.csproj]
To fix this either user `Ignore( ... )`, use a declaration `let _ = ...` or change the return type of the function to `Unit`.
```

**Screenshots**

**System information**

- Version of the NuGet package or extension for which the problem occurs
- Your operating system and .NET Core version  
- For issues with extensions, the version of the IDE for which the problem occurs 

**Additional context**

**Comment by bettinaheim** [comment]
@samarsha This used to have a more descriptive error message ""Expecting expression of type Unit. Only expressions of type Unit can be used as expression statements." Could you please take a look and give a dedicated message again?

**Comment by samarsha** [comment]
> Could please also double check what kind of error we are giving for what used to be the MissingFunctorSupport, ExcessFunctorSupport and FunctorSupportMismatch diagnostic?

These all use the standard type mismatch error message, e.g.

```
The type (Unit => Unit) does not match the type (Unit => Unit is Adj).
Actual type:   (Unit => Unit)
Expected type: (Unit => Unit is Adj)
```

For type mismatches in a double negative position (e.g. situations where ExcessFunctorSupport could originally happen, I think), the error message is confusing. I filed #1335.

**Comment by bettinaheim** [comment]
> > Could please also double check what kind of error we are giving for what used to be the MissingFunctorSupport, ExcessFunctorSupport and FunctorSupportMismatch diagnostic?
> 
> These all use the standard type mismatch error message, e.g.
> 
> ```
> The type (Unit => Unit) does not match the type (Unit => Unit is Adj).
> Actual type:   (Unit => Unit)
> Expected type: (Unit => Unit is Adj)
> ```
> 
> For type mismatches in a double negative position (e.g. situations where ExcessFunctorSupport could originally happen, I think), the error message is confusing. I filed #1335.

@samarsha  That looks understandable to me, to I don't think there is a need to change that. Thanks for checking!
