### ISSUE TITLE
LLVM QIR Target Example

### ISSUE THREAD

**Issue by chemix-lunacy** [microsoft/qsharp-compiler#1107]
Hey.

This is just a quick question, so sorry if it's the wrong place! (I'll add the tag once created if I can)

I've been tinkering with getting LLVM to process QIR but it's been slow going. Do you have an example LLVM target (either whole or in part) that I could use as a reference? I had a look around but couldn't find anything readily to hand, though it might be lurking somewhere. My main issues right now are around dealing properly with the various quantum intrinsics and how they get built/flow through the usual pipeline, so anything around those areas would be immensely helpful. 

Also as a side question: I noticed mention that you'd be moving more to LLVM in the future. I'm just curious to how that'd look - would you build a mostly-complete LLVM target for people to use as needed?

Thanks!

**Comment by chemix-lunacy** [comment]
Gonna close this as not to clutter up the issues list and might not be the place to ask - also started making headway so I'll keep tinkering.

**Comment by bettinaheim** [comment]
@chemix-lunacy This is definitively a good place to ask - I just hadn't gotten to respond yesterday. :) 
Could you give me a bit more context regarding what exactly you are looking into doing? 
We would love to help engage with it, and realize that we haven't got all the documentation and examples ready for that just yet.

In the meantime:
For execution on a simulator, we just use the clang toolchain to build the executable and provide the native runtime for CPU execution (the libraries that simply implement the functions required by the QIR specs are just that; they are libraries with implementations that are linked in and can be found here: https://github.com/microsoft/qsharp-runtime/tree/main/src/Qir/Runtime).
We currently do not have any public custom code generators, and any code generators in the LLVM sense for QPU execution are implemented by the hardware provider.
As an FYI, the current setup is somewhat documented [here](https://github.com/microsoft/qsharp-compiler/tree/main/examples/QIR/Optimization), and we have started to look into custom passes [here](https://github.com/microsoft/qsharp-compiler/tree/features/llvm-passes/src/Passes).

**Comment by chemix-lunacy** [comment]
@bettinaheim Ah, was a bit pre-emptive on the close!

Thanks for the links, especially the last two - missed those or they got added since I last checked and might come in very handy. What I'm trying to do likely falls under your comment about LLVM code generators: taking in the QIR and spitting out HW-specific instructions using LLVM itself. I was wondering if you had (or planned to have) some examples to help build such a code-gen, but sounds like it's probably a no? 

Totally understandable if so, but wanted to make sure.
