### ISSUE TITLE
Nested Conditional Blocks are Lifted when they Shouldn't Be

### ISSUE THREAD

**Issue by ScottCarda-MS** [microsoft/qsharp-compiler#1115]
**Describe the bug**

When a conditional includes nested conditionals that are invalid for lifting, the outer conditional may incorrectly be lifted into a generated callable by the ConditionallyControlled rewrite step. See discussion with concrete examples in comments here #767 (comment).

**To Reproduce**

Remove the Skip condition from [this test](https://github.com/microsoft/qsharp-compiler/blob/main/src/QsCompiler/Tests.Compiler/ClassicalControlTests.fs#L1631) in the ClassicallyControlledSupportTests.qs and run it. The test contains a nested condition with a return statement in it. Neither of the conditionals should be lifted into their own callables because of the return statement. However, the outer condition does get lifted, resulting in incorrect behavior.

**Expected behavior**

The test should pass. Because the inner conditional contains a return statement, neither the inner conditional nor the outer conditional should be lifted into their own callables.

**Comment by bettinaheim** [comment]
@ScottCarda-MS Based on the description, I thought this should be resolved with https://github.com/microsoft/qsharp-compiler/pull/1114 - is that not correct? The test case in the description is still commented out. If the issue is resolved with #1114, please enable the test case and close this issue.

**Comment by ScottCarda-MS** [comment]
> @ScottCarda-MS Based on the description, I thought this should be resolved with #1114 - is that not correct? The test case in the description is still commented out. If the issue is resolved with #1114, please enable the test case and close this issue.

This is not resolved with #1114. This is the more fundamental issue with lifting that has yet to be addressed. #1114 just prevented this issue from surfacing to the level of mattering for hardware jobs.

**Comment by ScottCarda-MS** [comment]
Resolved with #1277
