### ISSUE TITLE
TypedExpression.ExtractAll misses a case or two

### ISSUE THREAD

**Issue by yurysudz** [microsoft/qsharp-compiler#112]
**Describe the bug**

The extension method TypedExpression.ExtractAll in DataStructures doesn't seem to handle all cases, in particular, the CopyAndUpdate expression kind.

**To Reproduce**

Calling ExtractAll on a CopyAndUpdate expression does not apply the extractor function to sub-expressions.

**System information**

- Microsoft.Quantum.Compiler version 0.8.1907.1701

**Additional context**

Glancing at the method implementation, this appears to simply be a missed case in the pattern match. Same issue applies to TypedExpression.Exists. I'm not sure what a "NamedItem" is, but it also has a subexpression and might be another missed match case.

**Comment by bettinaheim** [comment]
Yes, you are right - looks like that whole file needs updating... Thanks for reporting!

**Comment by bettinaheim** [comment]
Fixed with PR #115.
