### ISSUE TITLE
Could not download Q# Language Server

### ISSUE THREAD

**Issue by ondrasek** [microsoft/qsharp-compiler#1127]
**Describe the bug**

When I try to create new Q# Project using the command palette, it always fails after a while with "Could not download Q# Language Server."

**To Reproduce**

1. Open VSCode (latest version, downloaded fresh from the web).
2. Install the Q# extension from the Marketplace (Extension ID: quantum.quantum-devkit-vscode)
3. Use command palette to run: "Q#: Create new project..." (command ID: quantum.newProject)
4. "Activating extensions" message appears at the bottom of the CSCode window. After a while, it is replaced by the "Downloading... message with progress in bytes."
5. The download repeats several times and fails after a while with message "Could not download Q# language server."
6. Debug log excerpt pasted below. 

The more information you can provide, the more likely someone will be successful at reproducing the issue and finding a fix.

**Expected behavior**

The Q# language server downloads and the new project is created.

**Screenshots**

N/A

**System information**

- Version of the NuGet package or extension for which the problem occurs
- Your operating system and .NET Core version  
- For issues with extensions, the version of the IDE for which the problem occurs 

**Additional context**

Debug log:
[Extension Host] [qsharp-lsp] Downloading https://msquantumpublic.blob.core.windows.net/qsharp-compiler/LanguageServer-osx-x64-0.18.2107153439.zip to /var/folders/0l/pddrzmgs41s8fx545ykv4hw40000gn/T/tmp-13121JAWNy89sMPrA.zip.
console.ts:137 [Extension Host] [qsharp-lsp] Expected SHA256 sum 79DD82CD12CF722200A5D90F2D26D03AC1212FE64C3576D2CC0FBB4C837D1D2B, got 820b8d6d493c86d21c02ad420306be359ffc294362ec99458d842e1d23b25460.
console.ts:137 [Extension Host] [qsharp-lsp] Error downloading language server: Error: Expected SHA256 sum 79DD82CD12CF722200A5D90F2D26D03AC1212FE64C3576D2CC0FBB4C837D1D2B, got 820b8d6d493c86d21c02ad420306be359ffc294362ec99458d842e1d23b25460.. 0 left.

**Comment by ondrasek** [comment]
Seems to be the same as #498 .

**Comment by cgranade** [comment]
Thanks for reporting this, @ondrasek! It looks like the SHA sums aren't matching on the downloaded file and the file that is expected, but I get the same SHA256 sum as you when I download the file manually, such that I doubt it's a connection issue or similar. I get similar mismatches for the Linux and Win10 zip files as well; @ricardo-espinoza, do you have any thoughts on this one?

**Comment by ondrasek** [comment]
Well, this is a fully automated process... I am _not_ downloading the file manually (it is downloaded by the VSCode extension). May be a CDN issue? Some CNDs servers/replicas having wrong file?

**Comment by ondrasek** [comment]
I just tried to download the file manually (curl) and using `shasum -b -a 256` renders the same hash as reported in the log, i.e. not the expected one. Just out of curiosity, I tried different SHA algorithms, to see if someone by any chance used a wrong SHA algo and truncated the hash, but that does not seem to be the problem.

**Comment by ondrasek** [comment]
```
shasum -a 256 < LanguageServer-osx-x64-0.18.2107153439.zip
820b8d6d493c86d21c02ad420306be359ffc294362ec99458d842e1d23b25460  -

❯ shasum -a 384 < LanguageServer-osx-x64-0.18.2107153439.zip
adbe10042bfd59593f2ef7cafd0358f1f99158d1abae0ccf20f1a45d8a6795a80b98281b15fef6cf1f7a0d4d35d20876  -

❯ shasum -a 512 < LanguageServer-osx-x64-0.18.2107153439.zip
f082d16c247174776a64bf8d64af2ae872445727a1bd0fbf2fb957984c71ce2a0069c1f9d6026a470c136546713d0ba2cd7392a61b62e29b4ab137bbbf68ff5c  -

❯ shasum -a 512224 < LanguageServer-osx-x64-0.18.2107153439.zip
97fbced8f328272e884d67c661ee54de7eb0924778e88b046659c9ab  -

❯ shasum -a 512256 < LanguageServer-osx-x64-0.18.2107153439.zip
69192e77f9e499141a2e3217b3eb709580da1a709211c370d2307248ef458dde  -
```

**Comment by ricardo-espinoza** [comment]
Thanks a lot for reporting this @ondrasek. We have now a good idea of what happened with the language server files. We're working on getting the ones with the right hash restored soon.

**Comment by YourLocalDundee** [comment]
i get the same issue as well and cant wait to get developing with Q# :)

**Comment by bettinaheim** [comment]
@ricardo-espinoza @cgranade I believe this should be resolved with the release in progress. Assigning to you - please close this once the issue is resolved.

**Comment by ondrasek** [comment]
Seems to work with the latest release. Requires VSCode extension to be updated. Can you elaborate on the solution though? Are we looking at a simple error by omission or a supply chain attack? ;-)

**Comment by ricardo-espinoza** [comment]
@ondrasek , @YourLocalDundee , we had an issue with the language server files produced for version 0.18.2107.153439 because they were accidentally modified last week causing the hash validation error that was affecting you. While that particular version still has the described issue, this is no longer a problem with new versions.

For those users affected by this, we recommend upgrading to 0.18.2108.160999.

**Comment by YourLocalDundee** [comment]
Upgrading worked for me and i have been able to get 2 of the test projects completed already. Thanks!
