### ISSUE TITLE
Allow documenting named items of UDTs

### ISSUE THREAD

**Issue by cgranade** [microsoft/qsharp-compiler#113]
**Is your feature request related to a problem? Please describe.**
Recently, Q# gained support for UDTs with named items; e.g.: `newtype Foo = (A: Int, (B: Bool, C: Qubit))`. At the moment, these named items aren't surfaced through to API documentation, such that the names aren't easy to use.

**Describe the solution you'd like**
```Q#
/// # Summary
/// ...
///
/// # Named Items
/// ## A
/// ...
/// ## B
/// ...
/// ## C
/// ...
newtype Foo = (A: Int, (B: Bool, C: Qubit))
```

**Comment by bettinaheim** [comment]
The only support that is needed here is in the docs parser, as long as this fits into the scheme. Do you want to take this one? :)

**Comment by bettinaheim** [comment]
Looks like this does not fit into our current OPS scheme. We will need support there before we can address this. @natke could you look into this?

**Comment by bettinaheim** [comment]
@cgranade I believe this should be addressed by the new code gen tool. Please reopen this and clarify if it isn't.
