### ISSUE TITLE
NamespaceItem items are incomplete in formatter

### ISSUE THREAD

**Issue by bettinaheim** [microsoft/qsharp-compiler#1216]
Since namespace items are incomplete, e.g. type declarations are not currently not processed by qsfmt. 

Namespace kinds that need support are:
- [x] Open Directives
- [x] Type Declarations

**Comment by yjt98765** [comment]
I have started to implement them. However, the ANTLR rule [`attribute`](https://github.com/microsoft/qsharp-compiler/blob/main/src/QsFmt/Parser/QSharpParser.g4#L35) confuses me:
```
attribute : at='@' expr=expression;

access : 'internal';

declarationPrefix : attributes+=attribute* access?;

// Type Declaration

typeDeclaration : declarationPrefix 'newtype' Identifier '=' underlyingType ';';
```
I cannot find related information in the Q# [user guide](https://docs.microsoft.com/en-us/azure/quantum/user-guide/language/programstructure/typedeclarations) or code examples in test files. Maybe it is a deprecated syntax and does not need to be implemented?

**Comment by yjt98765** [comment]
I see... It refers to the `@Attribute()`

**Comment by ScottCarda-MS** [comment]
Completed with #1239
