### ISSUE TITLE
Float data type and IntelliSense on qs code

### ISSUE THREAD

**Issue by bromeg** [microsoft/qsharp-compiler#126]
In the medical imaging domain; my input data is an array of complex numbers. The real and imaginary part of the complex number are float data types.
Unfortunately, using Double (what Q# offers) alters my output and that is not ok. A great suggestion would be to have the Float datatype available.

Another functionality that would be really useful is IntelliSense.
Right now, I first write code, build the project and fix issues.
It would be really great if IntelliSense could analyze Q# code in real time. If this functionality already exists, I’d be really curious how to activate it.

**Additional context**
Issue migrated from User Voice.

**Comment by bettinaheim** [comment]
I don't know when this was originally filed and by whom. We got IntelliSense with 0.3, so that part for the request is fairly obsolete.

**Comment by bettinaheim** [comment]
@bromeg I will actually close this issue - the IntelliSense part is done, and at this point I am not ready to introduce a float data type. That seems to be a precision issue in the pre- and post processing that should be addressed there.
