### ISSUE TITLE
Q# Formatter fails on valid Q# code

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp-compiler#1283]
**Describe the bug**

I used the Q# Formatter to update the deprecated code in the Katas, and on several of the projects it failed to parse the code. The same code builds successfully with Q# compiler, so it is not the case of invalid Q# code.

**To Reproduce**

1. Clone the [katas repo](https://github.com/microsoft/QuantumKatas/) and go to the KeyDistribution_BB84 folder.
2. Run `dotnet msbuild -t:UpdateSyntax`.
3. See error
    c:\GitHub\QuantumKatas\KeyDistribution_BB84\Tests.qs, Line 36, Character 121: extraneous input ')' expecting ';'
    c:\GitHub\QuantumKatas\KeyDistribution_BB84\Tests.qs, Line 36, Character 118: extraneous input 'e' expecting {',', ')'}

Projects MagicSquareGame and PhaseEstimation fail as well on multiple lines, and are worth looking into.

**Expected behavior**

Q# formatter correctly processes any valid Q# code.

**System information**

- QDK 0.21.2111177148
- .NET Core 3.1.415

**Comment by tcNickolas** [comment]
For MagicSquaresGame, the problematic code snippets are

    let rows = [[+1, +1, +1],
                [+1, -1, -1],
                [-1, +1, -1]];

    return [[(+1, [PauliX, PauliX]), (+1, [PauliX, PauliI]), (+1, [PauliI, PauliX])],
            [(+1, [PauliY, PauliY]), (-1, [PauliX, PauliZ]), (-1, [PauliZ, PauliX])],
            [(+1, [PauliZ, PauliZ]), (+1, [PauliI, PauliZ]), (+1, [PauliZ, PauliI])]] [row][column];

    return (sign * (Measure(paulis, target) == Zero ? +1 | -1)) == +1 ? Zero | One;

This looks like unary plus is not parsed correctly.

For PhaseEstimation, the issue is also unary plus.

**Comment by ScottCarda-MS** [comment]
> I will try to submit a PR soon (probably tomorrow) to solve it.

Thanks @yjt98765! I appreciate you taking the time to look into this! I look forward to reviewing your PR. I will go ahead and assign the issue to you. Let me know if you have any questions.

**Comment by yjt98765** [comment]
@tcNickolas Yes, it is the unary plus. I have added it to the grammar. With my pull request, all the test cases in QuantumKatas can be processes without errors. I did not check the result, though.

@ScottCarda-MS Thank you for assigning me!
