### ISSUE TITLE
Add the SparseSimulator support for the EntryPointDriver.

### ISSUE THREAD

**Issue by kuzminrobin** [microsoft/qsharp-compiler#1326]
Once the [Sparse Simulator PR](https://github.com/microsoft/qsharp-runtime/pull/918) is merged to the feature branch (or in parallel with that), add a feature branch to the Q# Compiler repo to support the Sparse Simulator for the EntryPointDriver. [Details](https://github.com/microsoft/qsharp-runtime/pull/918#discussion_r792327069).

After that make sure that in the `BasicExecution` test (in Q# Runtime repo) the Sparse Simulator-related block is uncommented and the test succeeds (`Microsoft.Quantum.Simulation.Simulators.Tests.CoreTests.BasicExecution`, CoreTests.cs line 34). Currently it fails: 
```
dotnet TestProjects/QSharpExe/bin/Debug/netcoreapp3.1/QSharpExe.dll --simulator SparseSimulator2
The simulator 'SparseSimulator2' could not be found.

If 'SparseSimulator2' is a custom simulator, it must be set in the DefaultSimulator project property:

<PropertyGroup>
<DefaultSimulator>SparseSimulator2</DefaultSimulator>
</PropertyGroup>
```

**Comment by bettinaheim** [comment]
Here is the PR: https://github.com/microsoft/qsharp-compiler/pull/1338
This PR needs to be coordinated with the runtime repo.

**Comment by kuzminrobin** [comment]
Resolved [here](https://github.com/microsoft/qsharp-runtime/pull/939/files#diff-38805c4f5465e4e8ae8e48521c2712723a407941919d611f0735d8a754d067ff).
