### ISSUE TITLE
Extend code action suggesting replacement for array item updates

### ISSUE THREAD

**Issue by sw23** [microsoft/qsharp-compiler#135]
A code action for simple array update expressions was added on #78

This feature request is to extend the code action to handle more complicated cases (as identified by @vadym-kl)
- `arr[i] = 1` -> `set arr w/= i <- 1;`
- `{set }arr[i][j] = 1` -> `set arr w/= i <- ( set arr[j] w/= j <- 1 );`

**Comment by bettinaheim** [comment]
@sw23 Thank you for picking this up! 
Sorry, I meant to assign that to you - will fix as soon as I get back to my desk. 
I am looking forward to this contribution!

**Comment by cgranade** [comment]
As a quick suggestion, I think the second code action might should be `set arr[i][j] = 1` → `set arr w/= i <- (arr[i] w/ j <- 1)`?

**Comment by bettinaheim** [comment]
Chris is correct - the rhs needs to be an expression. Thanks, didn't read the description careful enough!

**Comment by bettinaheim** [comment]
@sw23 I am not sure if you ever got the chance to pursue this. We are also looking into more general options for multi-dimensional arrays. Unless there is something you are actively working on, I suggest that I close this one, and instead open a suitable issue to reflect updated capabilities once we are ready with those.
