### ISSUE TITLE
Lambdas: Associativity across commas is too greedy in lambdas.

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-compiler#1356]
**Describe the bug**

When a lambda is specified in a list of other arguments, it interprets the other arguments as arguments to the lambda. For example, if `foo` takes a callable as its third argument and that callable is passed as a lambda, it will fail. So this code:
```qsharp
foo(firstArg, secondArg, lambda_arg => lambda_arg + 1);
```
is interpreted as if it was:
```qsharp
foo((firstArg, secondArg, lambda_arg) => lambda_arg + 1);
```
instead of:
```qsharp
foo(firstArg, secondArg, (lambda_arg => lambda_arg + 1));
```
Manually adding the parenthesis from the last example allows it compile as expected, but those parenthesis shouldn't be necessary.

**To Reproduce**

Use the following example code:
```qsharp
namespace lambda_bugbash {

    open Microsoft.Quantum.Canon;
    open Microsoft.Quantum.Intrinsic;
    open Microsoft.Quantum.Diagnostics;
    open Microsoft.Quantum.Arrays;
    
    @EntryPoint()
    operation main() : String {
        use q = Qubit();

        within {
            X(q);
        }
        apply {
            let testfunc = qs => CNOT(q, qs[0]);
            AssertOperationsEqualReferenced(1, testfunc, qs => X(qs[0]));
        }

        return "Success!";
    }
}
```

**Comment by samarsha** [comment]
> `foo(firstArg, secondArg, lambda_arg => lambda_arg + 1);`
> is interpreted as if it was:
> `foo((firstArg, secondArg, lambda_arg) => lambda_arg + 1);`

This is not quite a correct description of the bug. This example is parsed correctly. However, if `firstArg` is replaced by something like a literal `7` or `"foo"`, then parsing fails.

**Comment by swernli** [comment]
Oh, interesting! I didn't realize it was related to having a literal in the first argument. Good clarification!
