### ISSUE TITLE
nob

### ISSUE THREAD

**Issue by Bondzio** [microsoft/qsharp-compiler#136]
**Describe the bug**

Describe what the unexpected behavior or issue is. 
Please file a single issue per bug instead of enumerating multiple items.

**To Reproduce**

1. Open or go to '...'
2. Type or click on '....'
3. See error

The more information you can provide, the more likely someone will be successful at reproducing the issue and finding a fix.

**Expected behavior**

Describe what you expect to happen, versus what actually happened.

**Screenshots**

**System information**

- Version of the NuGet package or extension for which the problem occurs
- Your operating system and .NET Core version  
- For issues with extensions, the version of the IDE for which the problem occurs 

**Additional context**

**Comment by bettinaheim** [comment]
@bondzio Looks like this might have filed accidentally before being completed? 
Let me know what I can help with.
