### ISSUE TITLE
Adding an icon (Brand)

### ISSUE THREAD

**Issue by Chris2011** [microsoft/qsharp-compiler#148]
**Is your feature request related to a problem? Please describe.**
The product should represent a specific brand. So for this, Q# should have a nice looking logo. Like everything else.

**Describe the solution you'd like**
So the logo could have Q# in it, like the C# logo or it could look like the rectangle TS logo. Smth like in here: https://github.com/microsoft/BosqueLanguage/issues/94

**Describe alternatives you've considered**
Or just the phrase Q#

**Comment by Chris2011** [comment]
Or is there still an icon and I missed it? 🤔

**Comment by bettinaheim** [comment]
No, there is indeed no official logo so far. 
That's definitively something to look into though, thanks for the suggestion!

**Comment by bettinaheim** [comment]
Let's track this as part of https://github.com/microsoft/qsharp-compiler/issues/311.
