### ISSUE TITLE
Functor support can be auto generated even if outer blocks in conjugations do not provide the necessary support

### ISSUE THREAD

**Issue by vadym-kl** [microsoft/qsharp-compiler#149]
**Describe the bug**

Controlled variant auto-generation failure when using `within {...} apply {...}` statement,
if one of the operations used in `within` block has no controlled variant.

**To Reproduce**

Create `Bug.qs` file:
``` qsharp
namespace Buggy {
    operation U() : Unit is Adj {}
    operation V() : Unit is Adj + Ctl {}
    operation Foo() : Unit is Adj + Ctl {
        within { U(); }
        apply { V(); }
    }
}
```
Compiling causes the following error:
```
Bug.qs(5,18): error QS6312: The called operation does not support the necessary functor(s)
                                             for the requested auto-generation of a specialization. 
                                             Missing support for functor(s) Controlled. 
```

**Expected behavior**

File successfully compiles.

**System information**

- 0.9.1908.2906

**Comment by bettinaheim** [comment]
Yes, as I said, I did a minimal fix since the bug report came in very late and I didn't want to change much code going into the release. As I commented on that issue, I will put up a smarter functor generation shortly, but I didn't want to squeeze that into the release at short notice.

**Comment by vadym-kl** [comment]
I expected that `within {...} apply {...}` replicates behavior of 
* [ApplyWith](https://docs.microsoft.com/qsharp/api/qsharp/microsoft.quantum.canon.applywith) 
* [ApplyWithA](https://docs.microsoft.com/qsharp/api/qsharp/microsoft.quantum.canon.applywitha) 
* [ApplyWithC](https://docs.microsoft.com/qsharp/api/qsharp/microsoft.quantum.canon.applywithc) 
* [ApplyWithCA](https://docs.microsoft.com/qsharp/api/qsharp/microsoft.quantum.canon.applywithca) 

Here is a quote from Q# [documentation](https://docs.microsoft.com/quantum/language/statements#conjugations):
> Starting with our 0.9 release, we support a conjugation statement that implements the transformation above. Using that statement, the operation ApplyWith can be implemented in the following way:

This is not the case.  For example, the C# code generated for  method `Foo.ControlledBody` in the example in the issue is 
```csharp 
        public override Func<(IQArray<Qubit>,QVoid), QVoid> ControlledBody => (__in__) =>
        {
            var (__controlQubits__,__unitArg__) = __in__;
#line hidden
            U.Controlled.Apply((__controlQubits__, QVoid.Instance));
#line hidden
            V.Controlled.Apply((__controlQubits__, QVoid.Instance));
#line hidden
            U.Adjoint.Controlled.Apply((__controlQubits__, QVoid.Instance));
#line hidden
            return QVoid.Instance;
        }
```

and not 

```csharp 
        public override Func<(IQArray<Qubit>,QVoid), QVoid> ControlledBody => (__in__) =>
        {
            var (__controlQubits__,__unitArg__) = __in__;
#line hidden
            U.Apply( QVoid.Instance);
#line hidden
            V.Controlled.Apply((__controlQubits__, QVoid.Instance));
#line hidden
            U.Adjoint.Apply(QVoid.Instance);
#line hidden
            return QVoid.Instance;
        }
```
