### ISSUE TITLE
Rewrite the QIR RT related docs

### ISSUE THREAD

**Issue by kuzminrobin** [microsoft/qsharp-compiler#1560]
Rewrite the README.md in the following directories to reflect the latest updates done by [Replace C++ QIR Runtime with Rust QIR stdlib](https://github.com/microsoft/qsharp-runtime/pull/1087) PR.

qsharp-compiler\examples\QIR\Optimization\
qsharp-compiler\examples\QIR\Simulation\
qsharp-compiler\examples\QIR\Simulation\StateSimulator\
qsharp-compiler\examples\QIR\Simulation\TraceSimulator\
qsharp-compiler\src\QsCompiler\QirGeneration\

Related [PR](https://github.com/microsoft/qsharp-compiler/pull/1559).

---
@swernli, FYI.

**Comment by swernli** [comment]
The examples docs are rather different, and require a wholesale rewrite and move of the examples there. This is captured in #1577.
