### ISSUE TITLE
Q# Compiler repo is not updated for Rust QIR RT

### ISSUE THREAD

**Issue by kuzminrobin** [microsoft/qsharp-compiler#1569]
Related item: https://github.com/microsoft/qsharp-compiler/issues/1568.

Some files need to be updated for Rust QIR RT.
* `src\QsCompiler\TestTargets\Simulation\Target\QirExecution.cs`: `DllImport("Microsoft.Quantum.Qir.Runtime"`.
* `src\QsCompiler\TestTargets\Simulation\Target\Simulation.csproj`: "Microsoft.Quantum.Qir.Runtime" Version="**0.25.228311**-alpha"
* `examples\QIR\Optimization\README.md` refers out-of-date DLLs: Microsoft.Quantum.Qir.Runtime.dll, Microsoft.Quantum.Qir.QSharp.Foundation.dll, Microsoft.Quantum.Qir.QSharp.Core.dll; refers Microsoft.Quantum.Qir.Runtime 0.22.187631-alpha.
* `examples\QIR\JITCompilation\README.md` refers `0.18.2106148911-alpha` of Microsoft.Quantum.Qir.Runtime nuget
* `examples\QIR\Simulation\StateSimulator\README.md`
* `examples\QIR\Simulation\TraceSimulator\README.md`

**Comment by swernli** [comment]
The simulation examples should be rewritten and moved. Filed #1577 to track this.
