### ISSUE TITLE
Do not give completion suggestions in comments

### ISSUE THREAD

**Issue by bettinaheim** [microsoft/qsharp-compiler#178]
**Describe the bug**

Currently, fallback completions are given when typing comments. 

**Expected behavior**

I think it would be nicer to not give any completion suggestions in this case. 

**System information**

Irrelevant

**Comment by cgranade** [comment]
Would it be possible to make this conditional on a preference or configuration variable? Fallback completions in comments have been very helpful to me in writing API documentation comments. Thanks!
