### ISSUE TITLE
Support allocating a tuple of one qubit

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp-compiler#271]
**Describe the bug**

Trying to allocate a tuple of a single qubit variable (a single qubit or one array of qubits) fails with error QS6305 "The shape of the symbol tuple is not compatible with the assigned expression of type Qubit."

It seems fitting to support allocating tuples of single variables, since it would be consistent with Q#' overall approach to tuples.

**To Reproduce**

    using ((q) = (Qubit())) { }

**Expected behavior**

Successful allocation of the variable.

**System information**

QDK 0.10.1911.1607

**Comment by bettinaheim** [comment]
Thanks for filing! I can confirm the bug and will look into it.
