### ISSUE TITLE
Augment slice notation with an alternative that excludes the stop index

### ISSUE THREAD

**Issue by Strilanc** [microsoft/qsharp-compiler#30]
My Q# programs are filled with unnecessary `-1`s because the slice `a..b` includes `b` instead of stopping at `b-1`. I recommend [copying ruby](http://ruby-doc.org/core-2.1.3/Range.html) and adding the alternative `a...b` to exclude `b`.

It would also be useful to have "open slices" like `a..` and `..b`. For example, `array[a..]` would be equivalent to `array[a..Length(array)-1]`.

**Comment by bettinaheim** [comment]
I am happy to say that as of Q# 0.8, open ranges are supported as contextual expressions for array slicing. We will update our docs shortly. This is the PR adding the documentation of the new capability to our docs: https://github.com/MicrosoftDocs/quantum-docs-pr/pull/459.

@Strilanc Let me know if you have any questions or other thoughts, and welcome to the Q# compiler repo! :)
