### ISSUE TITLE
Command line parameter --format MsBuild has no effect in response file

### ISSUE THREAD

**Issue by DmitryVasilevsky** [microsoft/qsharp-compiler#307]
**Describe the bug**

When "--format MsBuild" is specified in response file rather than on command line the error reporting is still in "Human Readable" format. Response files are widely used in MsBuild and Visual Studio fails to parse and report these errors correctly.

**To Reproduce**

1. Create response file
qsc.rsp:
--input a.qs
--format MsBuild

2. Create Q# file a.qs with errors

3. Run "dotnet qsc.dll build --response-files qsc.rsp"

4. See that errors are in "Human Readable" format:

Warning QS3101:
File: C:/Users/dmitryv/Documents/Q/TryQSC/a.qs
Position: [ln 2, cn 92]
Deprecated syntax. Use "is Ctl+Adj" to denote the operation characteristics instead.

5. Move "--format MsBuild" to command line

6. Observe errors in MS Build format:

C:/Users/dmitryv/Documents/Q/TryQSC/a.qs(2,92): warning QS3101: Deprecated syntax. Use "is Ctl+Adj" to denote the operation characteristics instead.

**Expected behavior**

I expect --format switch to have the same effect on command file and in response file.

**Screenshots**

![WrongFormat](https://user-images.githubusercontent.com/60718360/73969007-736a5500-48cf-11ea-8235-fa5bbabfda2f.PNG)

**System information**

.nuget\packages\microsoft.quantum.sdk\0.10.2001.1505-alpha

**Comment by bettinaheim** [comment]
Yes, same for -v (verbose mode). The --response-file parameter is not processed as nicely as it should. Hopefully we'll get around to do some clean up soon-ish.

**Comment by bettinaheim** [comment]
I fixed this - PR is coming soon.
