### ISSUE TITLE
Q# compilation fails if user name contains accented characters

### ISSUE THREAD

**Issue by Piedone** [microsoft/qsharp-compiler#33]
Similarly to #48 compilation also throws errors if your username is "Zoltán", most possibly due to an accented character being there. However, I'm not sure; I just know that this fails, while a user account named "Qsharp" works.

Specifically when I try to build the samples I get errors of this sort for all projects:

> Severity	Description	Project
> Error	The command "dotnet "d:\Users\Zoltán\.nuget\packages\microsoft.quantum.development.kit\0.4.1901.3104\build\../tools/qsc/qsc.dll" build --format MsBuild  --input "SimpleIsing.qs" --references "d:\Users\Zoltán\.nuget\packages\microsoft.quantum.development.kit\0.4.1901.3104\lib\netstandard2.0\Microsoft.Quantum.Primitives.dll" "d:\Users\Zoltán\.nuget\packages\microsoft.quantum.development.kit\0.4.1901.3104\lib\netstandard2.0\Microsoft.Quantum.QsCompilerCommon.dll" "d:\Users\Zoltán\.nuget\packages\microsoft.quantum.development.kit\0.4.1901.3104\lib\netstandard2.0\Microsoft.Quantum.Simulation.Common.dll" "d:\Users\Zoltán\.nuget\packages\microsoft.quantum.development.kit\0.4.1901.3104\lib\netstandard2.0\Microsoft.Quantum.Simulation.Core.dll" "d:\Users\Zoltán\.nuget\packages\microsoft.quantum.development.kit\0.4.1901.3104\lib\netstandard2.0\Microsoft.Quantum.Simulation.QCTraceSimulatorRuntime.dll" "d:\Users\Zoltán\.nuget\packages\microsoft.quantum.development.kit\0.4.1901.3104\lib\netstandard2.0\Microsoft.Quantum.Simulation.Simulators.dll" --output obj\qsharp\src\" exited with code -3.	SimpleIsingSample
> 

There are a few with error code -2 too:

> Severity	Description	Project
> Error	The command "dotnet "d:\Users\Zoltán\.nuget\packages\microsoft.quantum.development.kit\0.4.1901.3104\build\../tools/qsc/qsc.dll" build --format MsBuild  --input "AdiabaticIsing.qs" --references "E:\Projects\Munka\Lombiq\MicrosoftQuantumDevelopmentKitSamples\Samples\src\IsingGenerators\bin\Debug\netcoreapp2.0\IsingGeneratorsSample.dll" "d:\Users\Zoltán\.nuget\packages\microsoft.quantum.canon\0.4.1901.3104\lib\netstandard2.0\Microsoft.Quantum.Canon.dll" "d:\Users\Zoltán\.nuget\packages\microsoft.quantum.development.kit\0.4.1901.3104\lib\netstandard2.0\Microsoft.Quantum.Primitives.dll" "d:\Users\Zoltán\.nuget\packages\microsoft.quantum.development.kit\0.4.1901.3104\lib\netstandard2.0\Microsoft.Quantum.QsCompilerCommon.dll" "d:\Users\Zoltán\.nuget\packages\microsoft.quantum.development.kit\0.4.1901.3104\lib\netstandard2.0\Microsoft.Quantum.Simulation.Common.dll" "d:\Users\Zoltán\.nuget\packages\microsoft.quantum.development.kit\0.4.1901.3104\lib\netstandard2.0\Microsoft.Quantum.Simulation.Core.dll" "d:\Users\Zoltán\.nuget\packages\microsoft.quantum.development.kit\0.4.1901.3104\lib\netstandard2.0\Microsoft.Quantum.Simulation.QCTraceSimulatorRuntime.dll" "d:\Users\Zoltán\.nuget\packages\microsoft.quantum.development.kit\0.4.1901.3104\lib\netstandard2.0\Microsoft.Quantum.Simulation.Simulators.dll" --output obj\qsharp\src\" exited with code -2.	AdiabaticIsingSample

Should this rather go to https://quantum.uservoice.com/forums/906943-setup-and-visual-studio-vs-code-integration?

**Comment by bettinaheim** [comment]
Thank you for reporting & welcome to the Q# compiler repo!
We'll take a look, but it might take some time with a lot of exciting things going on, like the creation of this public repo. :) With everything being open source now, there is of course always a chance that someone from the community might lend us a helping hand!

**Comment by samarsha** [comment]
I can't reproduce this issue with a Windows user account named "Zoltán". These steps work for me and the SimpleIsingSample project builds successfully:

```
PS C:\Users\Zoltán> git clone https://github.com/microsoft/Quantum.git
PS C:\Users\Zoltán\Quantum> cd .\samples\simulation\ising\simple\
PS C:\Users\Zoltán\Quantum\samples\simulation\ising\simple> dotnet build
...
  ____________________________________________

  Q#: Success! (0 errors, 0 warnings)

  SimpleIsingSample -> C:\Users\Zoltán\Quantum\samples\simulation\ising\simple\bin\Debug\netcoreapp3.1\SimpleIsingSample.dll
...
```

(Same result with AdiabaticIsingSample.)

@Piedone Would it be possible to try this again and see if the issue is still there? :)

**Comment by Piedone** [comment]
I think I've built the project from Visual Studio, should that make a difference. I just tried that with the simulation.sln solution and I get no errors, neither by building the project directly as you did. So it seems the issue is resolved in the current version, thank you!

Feel free to keep the user account if you like the name :D.

**Comment by samarsha** [comment]
That's great! Thanks for following up.

I'll add a basic test for building a project containing accented characters in the file path to try to prevent this bug from reoccurring, although I don't know what the exact cause was. (Also, unfortunately the project build tests happen to be in a private repository at the moment, so I can't link to it.)

I will keep the account for a little while. :)
