### ISSUE TITLE
Bug found when cloned repo is in folders with space in their names

### ISSUE THREAD

**Issue by KittyYeungQ** [microsoft/qsharp-compiler#333]
**Describe the bug**

Bug found while trying to build library files when cloned repo is in folders with space in their names. 

**To Reproduce**

1. Edit a .qs file in the QuantumLibraries/Standard/src that's cloned into local folders with space in their names. In this case, "Quantum Computing" and "Doc PR" both have spaces. 
2. dotnet build
3. See error

![image](https://user-images.githubusercontent.com/59890648/75199463-04d32700-5718-11ea-8331-6fc588623c28.png)

**Comment by bettinaheim** [comment]
That is weird because our sanity tests specifically tests projects with spaces in the path. We'll look into it, and also why this isn't picked up by our sanity tests.

**Comment by deonlewisduke** [comment]
There's a quantum effect you didn't take into account. In the xref:titleofexists.var source add some type of replace upon or if than command? I don't know I'm just a bored homeless guy.
