### ISSUE TITLE
Consider using Coding Style and .editorconfig

### ISSUE THREAD

**Issue by rstm-sf** [microsoft/qsharp-compiler#342]
Hello!

Please, consider using Coding Style and [.editorconfig](https://editorconfig.org/). Because it’s unusual to see, for example, the following code

https://github.com/microsoft/qsharp-compiler/blob/9bdc21409409b8e74cde1e0a24c49fc80bb602f3/src/QsCompiler/Compiler/CompilationLoader.cs#L408-L409

**Comment by marshallsa** [comment]
Thanks for the suggestion! We've discussed standardizing the coding style recently. An .editorconfig file sounds like a good idea. It looks like a lot of editors have support for it, including [Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019) and [Visual Studio Code](https://github.com/editorconfig/editorconfig-vscode).

We're also interested in tools to automatically check code style, for example as part of the automated builds for PRs. It looks like [dotnet-format](https://github.com/dotnet/format) can do this, but we're open to other suggestions.

**Comment by filipw** [comment]
In C# extension in VS Code, editorconfig support is an opt in flag for OmniSharp (https://www.strathweb.com/2019/07/editorconfig-support-in-omnisharp-and-c-extension-vs-code/), we hide most of these newer features behind an opt-in flag on order to keep the base featureset is as lightweight as possible. but yes it definitely makes sense to me too!

For enforcing code style at build time you can also have a look at `Microsoft.CodeAnalysis.CSharp.CodeStyle` prerelease package (only exists on Roslyn CI feed). It ships support for whitespace (IDE0055) violations (same as those covered by dotnet-format) in a regular analyzer package and reads the settings from editorconfig file.

**Comment by cgranade** [comment]
We actually have an [editorconfig for the samples repo](https://github.com/microsoft/Quantum/blob/master/.editorconfig) for precisely this reason. We've looked into using dotnet-format with precommit before to help with code style, but to limited success.

**Comment by marshallsa** [comment]
I'm starting to work on an [.editorconfig file in the marshallsa/editorconfig branch](https://github.com/microsoft/qsharp-compiler/blob/marshallsa/editorconfig/.editorconfig). Some mixed results so far.

First, it seems like the only way to reformat @rstm-sf's `foreach` example is to set `csharp_preserve_single_line_blocks = false`. However, this also reformats auto-properties that are defined on one line:

```
public int Foo { get; set; }
```

becomes

```
public int Foo
{
    get; set;
}
```

I think this is unnecessary, but I can't find a way to apply the reformatting to `foreach` without also applying it to auto-properties. So it's not ideal, but maybe worth it?

Second, it seems like Visual Studio does not support reformatting F# files at all. So unfortunately we might have to manually enforce an F# coding style. At least it could still be a good idea to write out some of the rules explicitly so we can refer back to them (probably based on the [F# style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) with a few modifications), unless someone knows another way to auto-format F#.

**Comment by rstm-sf** [comment]
It seems to me that the following option looks better `csharp_preserve_single_line_blocks = false` :)

It seems that I was mistaken in that I looked at the settings of editorconfig from far: for such a case it is difficult to choose an option. Maybe because it is not popular? Before that, I saw two equivalent options:
```
for ()
    smth
```
and
```
for ()
{
    smth
}
```

But this was the first time I met such an option and it seems to me that it is _overloaded_: trying to fit everything on one line only complicates further support

**Comment by rstm-sf** [comment]
> Second, it seems like Visual Studio does not support reformatting F# files at all. So unfortunately we might have to manually enforce an F# coding style. At least it could still be a good idea to write out some of the rules explicitly so we can refer back to them (probably based on the [F# style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) with a few modifications), unless someone knows another way to auto-format F#.

There is a [Fantomas](https://github.com/fsprojects/fantomas) project. It also has an issue supporting editorconfig  fsprojects/fantomas#650

**Comment by samarsha** [comment]
We reformatted all of the C# code using StyleCop, so the code sample mentioned in the original post has been fixed. :)

The F# code still has no formatting rules currently, though, so I'll leave this issue open until we do. Thanks @rstm-sf for pointing out Fantomas!
