### ISSUE TITLE
Q# Language Extension on dotnet core 3.1.200-preview

### ISSUE THREAD

**Issue by deviousasti** [microsoft/qsharp-compiler#365]
On VS 2019 Preview 5.0
Language Extension fails, leading to broken Intellisense for all packages.

```
Error: MSBuild error in C:\Program Files\dotnet\sdk\3.1.200-preview-015002\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(59,5): The "ProcessFrameworkReferences" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Frameworks, Version=5.5.0.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'NuGet.Frameworks, Version=5.5.0.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

![image](https://user-images.githubusercontent.com/2375486/76337791-deb7a480-631d-11ea-841d-d2ab57d186a2.png)

Has PR #359 been deployed?

**Comment by bettinaheim** [comment]
@deviousasti No, #359  has not yet been released. However, if you look at the [corresponding build](https://dev.azure.com/ms-quantum-public/Microsoft%20Quantum%20(public)/_build/results?buildId=8455&view=results) and click on Artifacts, then you should be able to download the (unsigned) alpha build based on that PR.

**Comment by deviousasti** [comment]
Uninstalled old package, installed new package (vsix) from build artifacts.
I'm still getting the same error.

I'm not exactly sure why qsharp is trying to use the `3.1.200-preview` in its build targets.
Interestingly, I can't seem to find this version [on Nuget](https://www.nuget.org/packages/NuGet.Frameworks/5.5.0-preview.2.6382). 5.5 is still in preview.

This is possibly related to #354

**Comment by bettinaheim** [comment]
> Uninstalled old package, installed new package (vsix) from build artifacts.
> I'm still getting the same error.
> I'm not exactly sure why qsharp is trying to use the 3.1.200-preview in its build targets.
> Interestingly, I can't seem to find this version on Nuget. 5.5 is still in preview.
> This is possibly related to #354

Could you run "dotnet --version" to confirm that you indeed are using 3.1.200-preview by default on your system? 
I suspect you may have the preview version of Visual Studio installed and updated it recently. I believe that update would pull in this dotnet version update as well. Unfortunately, we don't support using preview versions with our extension. Downgrading 3.1.102 would resolve the issue. My appologies for the hassle.

**Comment by deviousasti** [comment]
I switched the dotnet sdk from  3.1.200-preview to 3.1 LTS, and everything seems to be working now.
Thank you for your patience.

Closing this now.
