### ISSUE TITLE
Add Extensions.json and readme guidance for VSCode

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-compiler#374]
We should add a .vscode/extensions.json file to help recommend extensions for this repo. Also, while the Ionide extension is helpful for processing F# projects and the Omnisharp extension is recommended for C# projects, they have trouble playing well together. It took me a while to figure out how to get Ionide not to show errors for the C# projects that it fails to load and on the flip side how to avoid seeing thousands of errors registered by Omnisharp because it didn't understand namespaces that were coming from F# projects. I think we should add some additional guidance to the readme.md for vscode users to help with this set up.

_Originally posted by @swernli in https://github.com/microsoft/qsharp-compiler/pull/371/review_comment/create_

**Comment by bettinaheim** [comment]
Sounds good! Since you've dealt with this, do you want to make a stab at it, @swernli?

**Comment by swernli** [comment]
I can definitely do that!
