### ISSUE TITLE
Docs gen fails if previously generated docs file exist in the same folder

### ISSUE THREAD

**Issue by bettinaheim** [microsoft/qsharp-compiler#40]
**Describe the bug**

Running documentation generation twice in a row causes the second execution to fail due to a "key already exists" exception.

**To Reproduce**

1. Call the command line compiler specifying --doc "someFolder" (should build fine)
2. Do the same things again without deleting "someFolder" (fails)

**Expected behavior**

I think the best thing would be to just silently replace any content that already exists on disk, and maybe log a warning instead. @alan-geller and @anpaz-msft  for advice. 

**System information**

irrelevant 

**Additional context**

Mostly, we need to clarify what the correct behavior should be. 
The reason docgen reads the files in the folder is to handle the situation where you have a library namespace that spans multiple projects.

**Comment by alan-geller** [comment]
This might need some diagnosis as well as a (probably simple) code fix. Doc gen output files are always opened with mode Create, which should truncate and overwrite if the file exists and create a new file if the file doesn't exist.
One diagnostic tip is to provide a log file name to DoIgnoringExceptions in the Utils.cs file; this will write file-related exceptions (which can include file not found, among others that aren't actually errors) to the log file.
