### ISSUE TITLE
Auto-complete for function snippet in the VS Code extension missing field

### ISSUE THREAD

**Issue by crazy4pi314** [microsoft/qsharp-compiler#400]
The tab auto-complete for the function snippet in the VS Code extension doesn't tab though the input tag.

**To Reproduce**

In a *.qs file in VS Code where you have the Quantum Development Kit installed start typing "function" and arrow down to select the function snippet. The function name, output type and contents can be tabbed though but not the argument. 

**Expected behavior**

The input field should be tab-able like the rest of the fields.

**Screenshots**

**System information**
- Extension version:
```
Name: Microsoft Quantum Development Kit for Visual Studio Code
Id: quantum.quantum-devkit-vscode
Description: Microsoft Quantum Development Kit for Visual Studio Code provides support for developing quantum algorithms in the Q# programming language.
Version: 0.11.20033107
Publisher: Microsoft DevLabs
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=quantum.quantum-devkit-vscode
```
- Windows 10:
```
dotnet --version
3.1.101
```
- VS Code versions:
```
Version: 1.43.2 (system setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by bettinaheim** [comment]
Thanks for filing & fixing!
