### ISSUE TITLE
Commands for string manipulation don't work

### ISSUE THREAD

**Issue by geduardo** [microsoft/qsharp-compiler#429]
**Describe the bug**
The commands described in https://docs.microsoft.com/en-us/quantum/language/expressions#string-expressions to manipulate strings, `\n`, `\t`, `\r` do not work. Also `\"` avoids finishing the string literal but the compiler prints also the backslash, instead of only `"`. 

**To Reproduce**

Execute: 
```qsharp
Message("\"This line is not \n breaking \"");
```
And observe:
```dotnetcli
\"This line is not \n breaking \"
```

**Expected behavior**
Terminal printing: 
```dotnetcli
"This line is not
breaking "
```

**System information**

- Windows, .NET version: 3.1.100

**Additional context**

I tried executing the code in Python and in the Standalone command line, both show the same behaviour.

**Comment by bettinaheim** [comment]
Thanks for filing!

**Comment by samarsha** [comment]
I think this is the same as microsoft/qsharp-runtime#22 - it seems like a compiler bug, should the runtime issue be transferred/closed as a duplicate?

**Comment by samarsha** [comment]
I have transferred that issue to this repository as issue #458 - since it was filed first initially, I'll close this one, and we can can continue the discussion over there. :)
