### ISSUE TITLE
Escape sequences in string literals are not recognized

### ISSUE THREAD

**Issue by abacabadabacaba** [microsoft/qsharp-compiler#455]
The [documentation](https://docs.microsoft.com/en-us/quantum/user-guide/language/expressions#string-expressions) states that escape sequences such as `\n` in string literals are replaced with the corresponding characters. In fact, this doesn't happen. For example, `Message("a\nb");` should print `a` and `b` on separate lines, but it actually prints `a\nb`.

**Comment by samarsha** [comment]
Thanks for filing! I think that #458 was filed first (originally on qsharp-runtime - just transferred it over here). Let's keep tracking this bug in issue #458.
