### ISSUE TITLE
Identifiers with non-ASCII characters are not parsed correctly

### ISSUE THREAD

**Issue by abacabadabacaba** [microsoft/qsharp-compiler#464]
In general, Q# supports non-ASCII identifiers:
```
let Б = 1; // Compiles fine
```
However, it may break if such identifier starts with a keyword:
```
let isБ = 1; // Doesn't compile
```
Or, it may parse incorrectly:
```
let x = notБ; // Parsed as "not Б"
```

**Comment by DmitryVasilevsky** [comment]
Thanks for reporting this problem! We updated handling of non-ASCII characters in Q#. "isБ" and "notБ" should now be treated as identifiers.
