### ISSUE TITLE
Classical control transformation unconditionally executes `elif` conditions

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-compiler#475]
When transforming an if-elif pattern into `ApplyIfElseR` with nested `ApplyIf*` the compiler produces code that will end up evaluating the elif condition regardless of the result of the original if. This can change the behavior of code completely. Take for example this Q#:
```
    @EntryPoint()
    operation Test() : Unit {
        for (i in 0..10) {
            using (qs = Qubit[2]) {
                H(qs[1]);
                if (M(qs[0]) == Zero) {}
                elif (M(qs[1]) == Zero) {}
                H(qs[1]);
                let r = M(qs[1]);
                Message($"{r}");
                ResetAll(qs);
            }
        }
    }
```
Because qs[0] is left in the ground state, the if-statement will always be true, so the elif does not get evaluated, meaning the sequence of operations on qs[1] is always H, H, M. This should result in an output of "Zero" every time, and the untargeted simulator confirms this behavior. If you add an ExecutionTarget to the project that triggers the conditional rewrite, the resulting transformed code is effectively performing H, _M_, H, M on qs[1], so the output is a mix of "One" and "Zero" instead.

**Comment by ScottCarda-MS** [comment]
This will require a redesign of the feature. The issue currently is the lifting for the if contents happens first, then the reshaping of the if structures happens. So by the time we have a nested if-statement to lift, the lifting is already done.
