### ISSUE TITLE
Position of InvalidReassignmentInApplyBlock error is incorrect

### ISSUE THREAD

**Issue by samarsha** [microsoft/qsharp-compiler#491]
This Q# code is invalid because the `apply` block reassigns `foo`, which is used in the `within` block:

```
operation HelloQ() : Unit {
    mutable foo = false;
    within {
        let bar = foo;
    } apply {
        set foo = true;
    }
}
```

The error message should be on the `set foo = true;` line, but it's actually in the operation declaration:

![image](https://user-images.githubusercontent.com/33814365/85909609-adc98580-b7cf-11ea-8554-3de7b4c97ed5.png)

**Comment by bettinaheim** [comment]
@samarsha Since you already know the one line that needs to be changed and how, do you mind taking this one?
