### ISSUE TITLE
Build of faulty Q# program succeeds when calling `dotnet build` twice.

### ISSUE THREAD

**Issue by msoeken** [microsoft/qsharp-compiler#493]
**Describe the bug**

A faulty program compiles without reporting an error when compiled twice in a row without changing files.

**To Reproduce**

Run the following PS file.

```powershell
$project = @"
<Project Sdk="Microsoft.Quantum.Sdk/0.11.2006.403">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
</Project>
"@

$file = @"
namespace Namespace {
  open Microsoft.Quantum.Intrinsic;

  @EntryPoint()
  operation RunProgram() : Unit {
    Message("Error / No Error")
  }
}
"@

Set-Content -Path project.csproj $project
Set-Content -Path operation.qs $file

dotnet build
dotnet build

Remove-Item -Path project.csproj
Remove-Item -Path operation.qs
```

**Expected behavior**

I expect that the compilation fails twice, what actually happens:

```text
Microsoft (R) Build Engine version 16.7.0-preview-20271-03+ba9a1d64a for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored ...\project.csproj (in 1.25 sec).
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  Determining projects to restore...
  All projects are up-to-date for restore.
.../operation.qs(6,32): error QS2003: Expecting semicolon. [...\project.csproj]
  
  ____________________________________________

  Q# compilation failed: 1 error, 0 warnings
  
...\Sdk.targets(116,5): error MSB3073: The command "dotnet ".../qsc.dll" build --format MsBuild -v Normal --response-files obj/qsharp/config/qsc.rsp" exited with code -3. [...\project.csproj]

Build FAILED.

.../operation.qs(6,32): error QS2003: Expecting semicolon. [...\project.csproj]
...\Sdk.targets(116,5): error MSB3073: The command "dotnet ".../qsc.dll" build --format MsBuild -v Normal --response-files obj/qsharp/config/qsc.rsp" exited with code -3. [...\project.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:15.13
Microsoft (R) Build Engine version 16.7.0-preview-20271-03+ba9a1d64a for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  Determining projects to restore...
  All projects are up-to-date for restore.
  project -> ...\project.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.20
```

**Screenshots**

**System information**

- NuGet package: 0.11.2006.403
- Win 10 Ent. 1909, .NET Core 3.1 and macOS Catalina Version 10.15.5

**Comment by bettinaheim** [comment]
This is likely an issue with the incremental build and deleting the response file when the build fails should do the trick.

**Comment by QuarkNerd** [comment]
I would like to add to this, because I get a similar thing although in my case I don;t think the code is faulty

csProj ```namespace qSharp_begins {
    open Microsoft.Quantum.Convert;
    open Microsoft.Quantum.Math;
    open Microsoft.Quantum.Measurement;
    open Microsoft.Quantum.Canon;
    open Microsoft.Quantum.Intrinsic;

    @EntryPoint
    operation GenerateRandomNumber() : Int {
        mutable bits = new Result[0];


        for (idxBit in 1..BitSizeI(50)) {
            set bits += [SampleQuantumRandomBitGenerator()];
        }

        let sample = ResultArrayAsInt(bits);
        return sample;
    }


    operation SampleQuantumRandomBitGenerator() : Result {
        using (q = Qubit())  {  // Allocate a qubit.
            H(q);               // Put the qubit to superposition. It now has a 50% chance of being 0 or 1.
            return MResetZ(q);  // Measure the qubit value.
        }
    }
}
```

Program ```namespace qSharp_begins {
    open Microsoft.Quantum.Convert;
    open Microsoft.Quantum.Math;
    open Microsoft.Quantum.Measurement;
    open Microsoft.Quantum.Canon;
    open Microsoft.Quantum.Intrinsic;

    @EntryPoint
    operation GenerateRandomNumber() : Int {
        mutable bits = new Result[0];


        for (idxBit in 1..BitSizeI(50)) {
            set bits += [SampleQuantumRandomBitGenerator()];
        }

        let sample = ResultArrayAsInt(bits);
        return sample;
    }


    operation SampleQuantumRandomBitGenerator() : Result {
        using (q = Qubit())  {  // Allocate a qubit.
            H(q);               // Put the qubit to superposition. It now has a 50% chance of being 0 or 1.
            return MResetZ(q);  // Measure the qubit value.
        }
    }
}
```

I run `dotnet run` in BASH on Win10, .net Core SDK 3.1.201.
First time I get the ` error QS3238: Expecting a argument tuple of compile time constants`, after that it just works

**Comment by msoeken** [comment]
@QuarkNerd Thanks for your comments. I just want to clarify that there is indeed a syntax error present in your example. It should be `@EntryPoint()` instead of `@EntryPoint`.

**Comment by bettinaheim** [comment]
@QuarkNerd Could you confirm the Microsoft.Quantum.Sdk version that you are using? Just to confirm that this is indeed the same issue related to the incremental build.

**Comment by QuarkNerd** [comment]
> @QuarkNerd Thanks for your comments. I just want to clarify that there is indeed a syntax error present in your example. It should be `@EntryPoint()` instead of `@EntryPoint`.

Ah sorry, my bad. Very new to q#


> @QuarkNerd Could you confirm the Microsoft.Quantum.Sdk version that you are using? Just to confirm that this is indeed the same issue related to the incremental build.

"Microsoft.Quantum.Sdk/0.11.2006.403", forgot to add to original comment

**Comment by msoeken** [comment]
This issue can become quite a problem, when you run `dotnet build` the first time, observe an error, and then run `dotnet build -v diag` to see more details without changing any files. Then, the compilation succeeds without reporting any errors.
