### ISSUE TITLE
openExternal is not defined for vscode.env in the Visual Studio Code extension

### ISSUE THREAD

**Issue by marshallsa** [microsoft/qsharp-compiler#51]
**Describe the bug**

Visual Studio Code says that `openExternal` isn't defined:

```
{
	"resource": "/c:/Users/t-samars/source/repos/qsharp-compiler/src/VSCodeExtension/src/dotnet.ts",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'openExternal' does not exist on type 'typeof env'.",
	"source": "ts",
	"startLineNumber": 27,
	"startColumn": 32,
	"endLineNumber": 27,
	"endColumn": 44
}
```

When I open the extension in debug mode it also pops up a message saying there's an error, and I have to click "Debug Anyway" to continue.

**To Reproduce**

1. Open the VSCodeExtension folder in Visual Studio Code
2. Open src/dotnet.ts or try to open the extension in debug mode

**Expected behavior**

The extension shouldn't have any type errors.

**Screenshots**

**System information**

- Visual Studio Code extension (Git master branch)
- Windows 10 1809, .NET Core 2.1.701
- Visual Studio Code 1.36.1

**Additional context**

The extension still works even with the error. I haven't tested the function so I'm not sure if `vscode.env.openExternal` really isn't defined at runtime, or if the type checker is wrong.

**Comment by cgranade** [comment]
This sounds like it could be a type checker bug, as we recently bumped the engine version. Does the issue persist if you rerun `npm install` in the extension package directory?

**Comment by marshallsa** [comment]
Oh, I had to run bootstrap.ps1 again before I ran `npm install`, but then it started working. Sorry about that!

**Comment by cgranade** [comment]
No worries at all, happy I could help!
