### ISSUE TITLE
Cannot run sample hello-world program from official Q# tutorial

### ISSUE THREAD

**Issue by pranavmarla** [microsoft/qsharp-compiler#550]
**Describe the bug**

I'm trying to get started with Q#. Following [the official tutorial](https://docs.microsoft.com/en-us/quantum/quickstarts/install-command-line?tabs=tabid-vscode), I installed the .NET Core SDK, the Microsoft Quantum Development Kit for Visual Studio Code extension and created a new standalone console application. As expected, VS Code automatically generated a sample hello-world Q# app.

However, frustratingly, I cannot actually run this program, since, when I type `dotnet run`, .NET complains about either an unexpected code fragment or about the lack of a 'Main' method (see attached screenshots) -- I tried to run the program multiple times, closing and opening VS Code, and the error message I got would fluctuate between these two.
Again, since this is a sample Q# app from the official Microsoft tutorial, I assume the code itself is correct -- can you please tell me what is the issue here, and how I can fix it? 

I was really looking forward to getting started with actually writing some Q# programs, so having the literal hello-world program fail to run is incredibly frustrating and demotivating.

**To Reproduce**

Not sure if this is relevant but, the first time I followed the [tutorial for programming Q# on VS Code](https://docs.microsoft.com/en-us/quantum/quickstarts/install-command-line?tabs=tabid-vscode), I completely missed the first prerequisite step (installing .NET Core SDK). Instead, I first installed the VS Code extension and, only later, with VS Code open, installed the .NET Core SDK.

In case that was the issue, I uninstalled both the VS Code extension and the .NET Core SDK, restarted my computer and then did it again in the recommended order: i.e. Install .NET Core SDK first (with VS Code closed), then open VS Code and install the extension. 
Unfortunately, the reinstallation made no difference.

**Expected behavior**

As per the [tutorial](https://docs.microsoft.com/en-us/quantum/quickstarts/install-command-line?tabs=tabid-vscode), I expected the sample app to run correctly.

**Screenshots**

I tried running the program multiple times by typing `dotnet run`, both in VS Code's terminal, and directly via Powershell -- every time, I would either get an error message about an unexpected code fragment, or about the lack of a 'Main' method.

First, in VS Code:
1. Error about no 'Main' method:
![vscode-error-1](https://user-images.githubusercontent.com/6486632/89134754-a3e52180-d4f5-11ea-96dc-c95e432984ea.PNG)

2. Error about 'Unexpected code fragment':
![vscode-error-2](https://user-images.githubusercontent.com/6486632/89134769-c37c4a00-d4f5-11ea-8eb9-a4fdd31c8772.PNG)

Next, directly via Powershell:
3. Error about no 'Main' method:
![powershell-error-1](https://user-images.githubusercontent.com/6486632/89134822-31c10c80-d4f6-11ea-9a36-f2dad447b93f.PNG)

4. Till now, I was only seeing the 'Unexpected code fragment' error in VS Code, not in Powershell. However when, in an attempt to get the program to run in Powershell, I first typed `dotnet clean` and then `dotnet run`, I got the 'Unexpected code fragment' error in Powershell as well:
![powershell-error-2](https://user-images.githubusercontent.com/6486632/89135020-18b95b00-d4f8-11ea-8225-0f08dcb9d236.PNG)

**System information**

Versions:
- Windows 10: `19041.388`
- .NET Core SDK: `3.1.302`
- VS Code: `1.47.3`
- Microsoft Quantum Development Kit for Visual Studio Code (VS Code Extension): `0.12.20072031`

Feel free to let me know if you need any more information.

**Comment by cgranade** [comment]
It looks like your Q# code is failing to compile due to the namespace name being invalid (`hello-world` has a hyphen, which isn't valid in an identifier name). That then causes there to not be any `Main` method in the code-behind generated by the Q# compiler, such that you get the error message shown. Does this persist if you change the namespace name to something like `HelloWorld`?

**Comment by pranavmarla** [comment]
That worked! Thank you so much, I never would have thought that!!

Would you happen to have a link to any documentation that lists exactly which characters are considered acceptable in an identifier (eg. hyphens are apparently bad, but what about underscores)?

**Comment by cgranade** [comment]
In this case, the hyphen character is used as the subtraction operator, such that `namespace hello-world` parses as defining a namespace whose name is the difference between `hello` and `world`. In general, Q# identifiers looks much like identifiers in other common language (identifiers must start with a lower- or upper-case letter or underscore, and can include digits after the first character).

**Comment by cgranade** [comment]
Since the issue sounds like it's been resolved, closing it now, but please feel free to re-open or to open a new one if something further comes up. Thanks!

**Comment by samarsha** [comment]
> Would you happen to have a link to any documentation that lists exactly which characters are considered acceptable in an identifier?

Unfortunately, I don't think we have documentation for this at the moment - the closest thing would probably be the Q# parser source code. I definitely agree that we should have more precise documentation for it and the rest of the Q# grammar, though.

**Comment by pranavmarla** [comment]
Great, thank you @cgrenade and @samarsha !

**Comment by leonardovenoso** [comment]
Change from Q-Test to QTest and be sure you have installed .net 3.x.
