### ISSUE TITLE
Combining type parameter resolutions succeeds when it shouldn't

### ISSUE THREAD

**Issue by bettinaheim** [microsoft/qsharp-compiler#583]
The following case and other similar cases (including direct recursions) should be indicated as invalid by TypeResolutionCombination:

    [<Fact>]
    [<Trait("Category","Type Resolution")>]
    member this.``Conflicting Resolution for type parameter in tuple`` () =
        let given = [|
            ResolutionFromParam [
                (FooA, BarA |> TypeParameter)
            ]
            ResolutionFromParam [
                (BarA, [Int; FooA |> TypeParameter] |> MakeTupleType)
            ]
        |]
        let expected = ResolutionFromParam [
            (BarA, [Int; FooA |> TypeParameter] |> MakeTupleType)
            (FooA, [Int; FooA |> TypeParameter] |> MakeTupleType)
        ]

        AssertCombinedResolutionFailure expected given

**Comment by ScottCarda-MS** [comment]
Closed with #587.
