### ISSUE TITLE
Default values for qubits and callables in uninitialized arrays cause runtime errors

### ISSUE THREAD

**Issue by samarsha** [microsoft/qsharp-compiler#589]
**Describe the bug**

Q# array initializers allow creating an array with default values for the given type. For callable and qubit types, the default value is an invalid callable and an invalid qubit.

**To Reproduce**

```
let f = (new (Int -> Int)[1])[0];
let _ = f(7);
```

> Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
> ---> Example.Main on C:\Users\samarsha\Desktop\QSharpProject\Program.qs:line 8

```
let q = (new Qubit[1])[0];
X(q);
```

> Unhandled exception. System.ArgumentNullException: Trying to perform a primitive operation on a null Qubit (Parameter 'q1')
> ---> Microsoft.Quantum.Intrinsic.X on :line 0
>   at Example.Main on C:\Users\samarsha\Desktop\QSharpProject\Program.qs:line 8

**Expected behavior**

There are no reasonable default values for qubits and callables, so Q# should make it harder or impossible to create them. In general, not every type will have a reasonable default, so there should be some way of requiring that a default exists before creating an array. One way to do this is make array constructors explicitly take in a value with which to initialize each cell.

**Comment by swernli** [comment]
Number 2 is especially dangerous, as `Default` allows you to create null qubits or null results pretty trivially:
```
    let q = Default<Qubit>();
    let r = Default<Result>();
    Message($"Values: [{q}] , [{r}]");
```
This code will output `Values: [] , []`, showing that both the variables are null.

**Comment by swernli** [comment]
It turns out, null `Result` variables allow for some very odd uses. They work in comparisons, but are neither `One` nor `Zero`, effectively making `Result` a ternary value instead of binary:
```
let r = Default<Result>();
if (r == Zero) {
    Message("Zero");
}
elif (r == One) {
    Message("One");
}
else {
    Message("Two?!?");
}
```
That code will output "Two?!?" which is both hilarious and ripe for abuse.

**Comment by samarsha** [comment]
Thanks for the great examples @swernli! It’s good to show that null is so dangerous *because* it’s useful for control flow, people will be tempted to use it, and it can spread throughout a code base and libraries, encouraging more people to use null or defensively check for null.

We should fix this and provide the type-safe alternative: an option type (#406).

**Comment by cgranade** [comment]
Items (1) and (2) are actually identical, of course:

```
function Default<'T>() : 'T {
    let array = new 'T[1];
    return array[0];
}
```

I think the notion of default values is incredibly useful in some contexts, but I agree it doesn't make any sense for some types (e.g.: `Qubit`). That could probably be rectified by having a concept indicating that a type supports default:

```
concept HasDefault when {
    function Default<'Self>() : 'Self;
}
example Int of HasDefault { ... }
example <'T> 'T[] of HasDefault {
    function Default() : 'T[] {
        return 'T[0];
    }
}
example <'T1, 'T2 where 'T1 is HasDefault, 'T2 is HasDefault> of HasDefault { ... }
```

**Comment by samarsha** [comment]
> Items (1) and (2) are actually identical, of course:

Yes - the implementation of `Default` is how I discovered this bug. :)

> I think the notion of default values is incredibly useful in some contexts, but I agree it doesn't make any sense for some types (e.g.: Qubit). That could probably be rectified by having a concept indicating that a type supports default:

In some contexts, yes, but I'm not sure that a universal default can be applied to a type without knowing that context. Array initializers think that the default `Int` is `0`, but `IndexOf` would say that the default `Int` is `-1`. In other cases, there is no reasonable default and you should use `None` from `Option<'T>` instead. I feel like default-ness depends too much on context to be a universal function.

**Comment by swernli** [comment]
@cgranade Pointed out to me that the documented default of `Result` is `Zero` which this behavior of returning null does not agree with. So for at least that case, the underlying implementation of the type should always construct a valid `Zero` result.
https://docs.microsoft.com/en-us/quantum/user-guide/language/expressions#array-creation

**Comment by samarsha** [comment]
Thanks for pointing out the default value table. There are several types which don't match that table:

* `Default<String>()` is `null` but should be `""`
* `Default<Result>()` is `null` but should be `Zero`
* `Default<Range>()` is `0..1..0` but should be `1..1..0`
* `Default<'T[]>()` is `null` but should be `new 'T[0]`

One way to fix the immediate issue is to update these defaults to match the table. But I think we should revisit the idea of having an "invalid" qubit or "invalid" callable at all.

With proper qubit lifetime management, we can make it impossible to obtain an invalid qubit (e.g. by preventing at compile-time putting a qubit into an array that outlives the `using` block). At that point uninitialized arrays will be the one remaining way to create a qubit that will crash the program, which would make using qubits in Q# unnecessarily unsafe.

Invalid callables are unavoidable as long as we have `fail` - but I still think you should have to opt *in* to creating a callable that will throw instead of opting *out*.

**Comment by samarsha** [comment]
I have created microsoft/qsharp-runtime#359 for the null/incorrect defaults issue, and repurposed this issue for discussing whether qubits and callables should have defaults (and in general whether every type needs to have a default, or if it should be opt-in like @cgranade mentioned).

**Comment by samarsha** [comment]
A random thought, but if every type needs a default value, then every type has at least one value, which means the void type cannot be represented in Q#. It's not used that often, but void can be useful for [proving at compile time that something will never happen](https://package.elm-lang.org/packages/elm/core/latest/Basics#Never).

**Comment by alan-geller** [comment]
I think modifying the "new" operator to take an initial value would be a good thing, and actually useful -- it makes it easier to create, say, an array of `PailiZ`s instead of an array of `PauliI`s. That way, we don't have to require a default value for every type, should we ever want to have a type with no values...
This would be a breaking change, though.

**Comment by cgranade** [comment]
> I think modifying the "new" operator to take an initial value would be a good thing, and actually useful -- it makes it easier to create, say, an array of `PailiZ`s instead of an array of `PauliI`s. That way, we don't have to require a default value for every type, should we ever want to have a type with no values...
> This would be a breaking change, though.

Odd idea: remove the `new` keyword, and make `Microsoft.Quantum.Arrays.ConstantArray` intrinsic.

**Comment by alan-geller** [comment]
> > I think modifying the "new" operator to take an initial value would be a good thing, and actually useful -- it makes it easier to create, say, an array of `PailiZ`s instead of an array of `PauliI`s. That way, we don't have to require a default value for every type, should we ever want to have a type with no values...
> > This would be a breaking change, though.
> 
> Odd idea: remove the `new` keyword, and make `Microsoft.Quantum.Arrays.ConstantArray` intrinsic.

Actually, I kind of like that...

**Comment by samarsha** [comment]
I like it too. :) The `new` keyword feels out of place in Q# since it's only used for arrays, but `new` is typically associated with constructing objects in OOP languages.

**Comment by cgranade** [comment]
```Q#
// tired:
mutable emptyArray = new 'T[0];
// wired:
mutable emptyArray = EmptyArray<'T>();
```

**Comment by swernli** [comment]
I agree, down with `new`! I really like @cgranade's `EmptyArray` suggestion.

**Comment by cgranade** [comment]
Out with the `new`, in with the... er... not new?

Anyway, all joking aside, getting rid of `new` takes a few more characters, but it's a lot more consistent with how we have expressed things elsewhere Q#. In particular, we can use intrinsic functions in Microsoft.Quantum.Arrays to include all existing functionality _except_ for the functionality that we would like to exclude.

Concretely, I'd start by proposing the following:

- Deprecate the `new` keyword.
- Introduce a new `EmptyArray<'T>() : 'T[]` function in Microsoft.Quantum.Arrays.
- Introduce a new function (not sure of best name) of type `(Range, (Int -> 'T)) -> 'T[]`, and perhaps of type `(Int, (Int -> 'T)) -> 'T[]` to prepopulate arrays from functions without needing another array to map from.
- Add a code action to suggest replacing `new 'T[0]` with `EmptyArray<'T>()`.
- Port samples and documentation examples which construct arrays with `mutable foo = new 'T[n]; for (idx in 0.. n - 1) { set foo[idx] w/= idx <- expr(); }` to use `Microsoft.Quantum.Arrays.DrawMany(n, expr, ())`.

Is there anything that I'm missing?

**Comment by alan-geller** [comment]
How about `EmptyArray<'T>` for a zero-length array and `ConstantArray<'T>(size : Int, element : 'T)` for bigger arrays.




> Out with the `new`, in with the... er... not new?
> 
> Anyway, all joking aside, getting rid of `new` takes a few more characters, but it's a lot more consistent with how we have expressed things elsewhere Q#. In particular, we can use intrinsic functions in Microsoft.Quantum.Arrays to include all existing functionality _except_ for the functionality that we would like to exclude.
> 
> Concretely, I'd start by proposing the following:
> 
> * Deprecate the `new` keyword.
> * Introduce a new `EmptyArray<'T>() : 'T[]` function in Microsoft.Quantum.Arrays.
> * Introduce a new function (not sure of best name) of type `(Range, (Int -> 'T)) -> 'T[]`, and perhaps of type `(Int, (Int -> 'T)) -> 'T[]` to prepopulate arrays from functions without needing another array to map from.
> * Add a code action to suggest replacing `new 'T[0]` with `EmptyArray<'T>()`.
> * Port samples and documentation examples which construct arrays with `mutable foo = new 'T[n]; for (idx in 0.. n - 1) { set foo[idx] w/= idx <- expr(); }` to use `Microsoft.Quantum.Arrays.DrawMany(n, expr, ())`.
> 
> Is there anything that I'm missing?

I think we still need `ConstantArray` to become intrinsic -- perhaps "guaranteed" is better than "intrinsic" -- as you said above, Chris.

We also need to figure out what to do with `Default<'T>`.

**Comment by cgranade** [comment]
> How about `EmptyArray<'T>` for a zero-length array and `ConstantArray<'T>(size : Int, element : 'T)` for bigger arrays.
>
> I think we still need `ConstantArray` to become intrinsic -- perhaps "guaranteed" is better than "intrinsic" -- as you said above, Chris.

`ConstantArray` already exists, so the change to make it intrinsic can be done without affecting the Q# API. `EmptyArray` should complement it nicely. We couldn't write `EmptyArray` in pure Q# using `ConstantArray`, though, without `Default<'T>`, such that it would need to be intrinsic as well.
 
> We also need to figure out what to do with `Default<'T>`.

Sounds like deprecate-and-drop, so that we can close the loophole where `Qubit` can be effectively `null`? If we want nullability, [explicit DUs and type-parameterized UDTs](https://github.com/microsoft/qsharp-compiler/issues/406) are the way to go, I think:

```
newtype Maybe<'T> = Some(Value : 'T) | None();
```

**Comment by alan-geller** [comment]
> > How about `EmptyArray<'T>` for a zero-length array and `ConstantArray<'T>(size : Int, element : 'T)` for bigger arrays.
> > I think we still need `ConstantArray` to become intrinsic -- perhaps "guaranteed" is better than "intrinsic" -- as you said above, Chris.
> 
> `ConstantArray` already exists, so the change to make it intrinsic can be done without affecting the Q# API. `EmptyArray` should complement it nicely. We couldn't write `EmptyArray` in pure Q# using `ConstantArray`, though, without `Default<'T>`, such that it would need to be intrinsic as well.

Yup.

> > We also need to figure out what to do with `Default<'T>`.
> 
> Sounds like deprecate-and-drop, so that we can close the loophole where `Qubit` can be effectively `null`? If we want nullability, [explicit DUs and type-parameterized UDTs](https://github.com/microsoft/qsharp-compiler/issues/406) are the way to go, I think:
> 
> ```
> newtype Maybe<'T> = Some(Value : 'T) | None();
> ```

Dropping `Default` would be a lovely thing to do. I think everything is simple if we drop it and `new` at the same time.

**Comment by cgranade** [comment]
One thought with dropping `new 'T[length]` that we may want to consider: creating default arrays of that form is sometimes used in functions like `Mapped` or `Interleaved` (the latter in progress at https://github.com/microsoft/QuantumLibraries/pull/320), where the length of the output array is known exactly. From rough and informal testing, "pre-allocating" in that way can result in an approximately 4× speedup over accumulating the output elements onto an empty array. That's definitely not a huge factor given that in practice the actual function being mapped will still overwhelm that, but I wanted to raise it for awareness nonetheless.

**Comment by alan-geller** [comment]
> One thought with dropping `new 'T[length]` that we may want to consider: creating default arrays of that form is sometimes used in functions like `Mapped` or `Interleaved` (the latter in progress at [microsoft/QuantumLibraries#320](https://github.com/microsoft/QuantumLibraries/pull/320)), where the length of the output array is known exactly. From rough and informal testing, "pre-allocating" in that way can result in an approximately 4× speedup over accumulating the output elements onto an empty array. That's definitely not a huge factor given that in practice the actual function being mapped will still overwhelm that, but I wanted to raise it for awareness nonetheless.

I guess the problem with using `ConstantArray` in this situation is that you don't know what the initial value should be. For the long term, it might be interesting to have some way to allocate an uninitialized array with some sort of (compiler-checked) commitment that every element is initialized before the array is either returned from the callable or passed as a parameter to another callable.

**Comment by cgranade** [comment]
> I guess the problem with using `ConstantArray` in this situation is that you don't know what the initial value should be. For the long term, it might be interesting to have some way to allocate an uninitialized array with some sort of (compiler-checked) commitment that every element is initialized before the array is either returned from the callable or passed as a parameter to another callable.

In many cases, we could kind of work around by doing something like using the first element of the output as the input to `ConstantArray`. In any case, I don't think this is a huge problem such that it should block deprecating `new`, so much as another usecase that might point to other features such as the one that you suggest.

**Comment by cgranade** [comment]
> Can't we make `ArrayInit<'a>(initializer : (Int -> 'a), count : Int)` instead, which can be implemented as an intrinsic and handle the uninitialized array internally?
> 
> ```qsharp
> function Mapped<'a, 'b>(mapper : ('a -> 'b), array : 'a[]) : 'b[] {
>     return ArrayInit(i -> mapper(array[i]), Length(array));
> }
> ```

That's effectively what the [`MappedOverRange` function](https://docs.microsoft.com/qsharp/api/qsharp/microsoft.quantum.arrays.mappedoverrange) does, with the slight modification that it acts on `Range` instead of `Int`. Using `Composed(mapper, ElementAt(_, array))` as the first input would also do it, even without lambdas. I think my main concern, though, would be with making sure we've carefully identified which functions and operations need to be intrinsic for a minimal working implementation of the Q# standard libraries; we should document somewhere that `EmptyArray<'T>` and `MappedOverRange<'T>` are part of that contract, perhaps?

**Comment by samarsha** [comment]
I think it would be nice if Q# could have built-in syntax for empty arrays, even without type inference necessarily - e.g. by allowing type annotations on expressions, so that

```qsharp
function EmptyArray<'a>() : 'a[] {
    return [] : 'a[];
}
```

I think `MappedOverRange` being intrinsic or not is a performance issue, which is important, but not necessary for a minimal working implementation, right?

**Comment by samarsha** [comment]
I created microsoft/qsharp-language#46 so that we can move forward with a proposal to remove `new` from the language. I think we can keep tracking this issue there instead.
