### ISSUE TITLE
Support for binary BigInt constants

### ISSUE THREAD

**Issue by msoeken** [microsoft/qsharp-compiler#610]
**Describe the solution you'd like**
For consistency, I suggest to support binary `BigInt` constants, e.g., `0b1100101011111110L`.

**Describe alternatives you've considered**
Alternatives are not using binary constants, e.g., `0xCAFEL` or converting a binary `Int` constant (if the value is small enough), e.g., `IntAsBigInt(0b1100101011111110)`.

**Comment by samarsha** [comment]
I noticed this a few days ago, too. I agree, I think it would make sense to support the same notations for `BigInt` that we do for `Int`. There is also octal notation `0o123` that does not work for `BigInt` with `0o123L`.

**Comment by cesarzc** [comment]
Please take a look at the `numericLiteral` function in [QsExpressionParsing.fs](https://github.com/microsoft/qsharp-compiler/blob/main/src/QsCompiler/TextProcessor/QsExpressionParsing.fs#L173) which is the one that parses Int, BigInt and Double literals.

Also, remember adding new cases to the `Expression literal tests` [test](https://github.com/microsoft/qsharp-compiler/blob/b19fe1705020a253c4ad867f966648128c95c3be/src/QsCompiler/Tests.Compiler/SyntaxTests.fs#L207) to make sure the new supported BigInt literals are parsed as expected.

**Comment by ziqi-ma** [comment]
Seems like C#'s NumberStyles Enum (argument of BigInteger.Parse) only supports hex? Does that mean we need to write our own logic of converting binary/octal strings to hex?

**Comment by cesarzc** [comment]
Hello Ziqi Ma, thanks for your interest in fixing this issue!

Yes, logic needs to be added to convert binary and octal strings to hex such that BigInteger.Parse can be used.

**Comment by cesarzc** [comment]
> 
> 
> Seems like C#'s NumberStyles Enum (argument of BigInteger.Parse) only supports hex? Does that mean we need to write our own logic of converting binary/octal strings to hex?
> Well, or slice it up and parse each part as int...
> And are we assuming the number is positive? (seems so from code?)

Hello Ziqi Ma, thanks for your interest in fixing this issue!

Yes, logic needs to be added to convert binary and octal strings to hex such that BigInteger.Parse can be used.

**Comment by samarsha** [comment]
> And are we assuming the number is positive? (seems so from code?)

I think this is correct. My understanding is that negative numbers are parsed as `negation-operator numeric-literal`, rather than parsing the `-` as part of the literal itself.
