### ISSUE TITLE
Order of evaluation in expressions can generate incorrect adjoints

### ISSUE THREAD

**Issue by samarsha** [microsoft/qsharp-compiler#615]
**Describe the bug**

When auto-generating an adjoint specialization, Q# reverses the order of statements, but does not reverse the order of evaluation in expressions. Because evaluation can have side effects, this means auto-generated adjoint specializations may apply operations in an incorrect order.

**To Reproduce**

```qsharp
operation Evaluator(a : Unit, b : Unit) : Unit is Adj { }

operation DoubleCNOT(a : Qubit, b : Qubit) : Unit is Adj {
    Evaluator(CNOT(a, b), CNOT(b, a));
}

@EntryPoint()
operation Demo() : Unit {
    using ((a, b) = (Qubit(), Qubit())) {
        within {
            X(a);
            DoubleCNOT(a, b);
        } apply { }
        Message($"({M(a)}, {M(b)})");
    }
}
```

Outputs `(Zero, One)` because the `within` block is not uncomputed correctly.

**Expected behavior**

The code above should output `(Zero, Zero)`, or it should not be allowed at all.

**System information**

Q# compiler v0.12.20082513

**Comment by samarsha** [comment]
One option to fix this is to implicitly lift operation calls in expressions into statements in the nearest scope, in order from left to right, so formally

```qsharp
Evaluator(CNOT(a, b), CNOT(b, a));
```

would be equivalent to

```qsharp
let x = CNOT(a, b);
let y = CNOT(b, a);
Evaluator(x, y);
```

Then order of evaluation would be well-defined, although this would also prevent this code from compiling because of QS6316: "Auto-generation of inversions is not supported for operations that contain operation calls outside expression statements."

**Comment by samarsha** [comment]
Actually, to clarify the above, the first line could be translated as

```qsharp
CNOT(a, b);
CNOT(b, a);
Evaluator((), ());
```

because `CNOT` returns `Unit`. Then adjoint generation would be possible without the bug here.

**Comment by swernli** [comment]
@samarsha Would the lifting only be necessary for operations that are themselves adjoint? As in, should a function be left inline, or should every callable in an expression get lifted unconditionally?

**Comment by swernli** [comment]
Also, it looks like this problem also applies to interpolated strings, so if `DoubleCNOT` were implemented as:
```qsharp
operation DoubleCNOT(a : Qubit, b : Qubit) : Unit is Adj {
    Message($"{CNOT(a, b)}, {CNOT(b, a)}");
}
```
then the same problem occurs. So whatever solution we use, we need to make sure it handles interpolated strings too.

**Comment by samarsha** [comment]
> Would the lifting only be necessary for operations that are themselves adjoint? As in, should a function be left inline, or should every callable in an expression get lifted unconditionally?

I think lifting needs to happen only to operation calls right before adjoint generation at the latest. There might be benefits to handling it consistently for all call expressions, but I don't think it's necessary for functions since they don't have side effects, and will probably increase the size of the AST and generated C#.
