### ISSUE TITLE
Generate a "main" function for an entrypoint in QIR

### ISSUE THREAD

**Issue by alan-geller** [microsoft/qsharp-compiler#638]
**Is your feature request related to a problem? Please describe.**
Currently QIR generation doesn't provide an equivalent to the Q#->C# generation for entrypoints. If you generate QIR and then compile to x64 code using clang, there is no `main` generated that will parse the command line and call the entrypoint.

**Describe the solution you'd like**
The QIR generator should emit a `main` function.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bettinaheim** [comment]
done/obsolete
