### ISSUE TITLE
Generate tuple/structure mapping code for QIR entrypoint wrappers

### ISSUE THREAD

**Issue by alan-geller** [microsoft/qsharp-compiler#639]
**Is your feature request related to a problem? Please describe.**
Currently the entrypoint wrappers created by the QIR generator map simple types and arrays of simple types, but not Q# tuples.

**Describe the solution you'd like**
Tuples in QIR should map to C structs in the C wrapper.
This _may_ require some facility to provide to the QIR generator the clang-mangled name of the LLVM structure that represents the C structure.

**Describe alternatives you've considered**
Because of the way name mangling works, it is difficult to do this by, for instance, giving a name to the LLVM structure used internally by QIR to represent a tuple, and then expose that structure to the calling C code.

**Additional context**
N/A

**Comment by bettinaheim** [comment]
This is done with PR #889.
