### ISSUE TITLE
Code action for deprecated unit type

### ISSUE THREAD

**Issue by miwertz** [microsoft/qsharp-compiler#64]
**Is your feature request related to a problem? Please describe.**

-- "()" being used for type and value 

**Describe the solution you'd like**

-- show code action that replaces the deprecated unit type "()" with "Unit"

**Describe alternatives you've considered**

**Additional context**

**Comment by bettinaheim** [comment]
The corresponding PR is https://github.com/microsoft/qsharp-compiler/pull/73.

**Comment by bettinaheim** [comment]
Merged into master with PR #130.
