### ISSUE TITLE
QIR generator code clean up

### ISSUE THREAD

**Issue by alan-geller** [microsoft/qsharp-compiler#641]
**Is your feature request related to a problem? Please describe.**
There's some ugly code in there...

**Describe the solution you'd like**
Some specific items:
- [obsolete/solved differently] Create a RuntimeFunctionBuilder that generates calls to runtime functions, including all prep code.
- [x] Track known information about values, such as lengths of array literals, and use it to simplify code.
- [x] In particular, simplify for loop condition evaluation when the loop direction is known.
- [x] Avoid materializing tuple literals that are immediately deconstructed, such as `let (a, b) = (1, 2);`.
- [obsolete/will be solved differently] Avoid generating callable values for partial applications that are only used locally.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bettinaheim** [comment]
@alan-geller I believe the subsequent work I did largely took care of those.
As for the partial applications, as part of implementing support for lambda expressions in Q#, I would like to just move the responsibility to properly lift lambdas and partial applications into a separate compiler pass, and remove the partial application handling from the QIR emission entirely. I'll hence go ahead and close this isse.
