### ISSUE TITLE
Port QIR generation to Linux and MacOS

### ISSUE THREAD

**Issue by alan-geller** [microsoft/qsharp-compiler#642]
**Is your feature request related to a problem? Please describe.**
The QIR generator relies on the [Llvm.NET](https://github.com/UbiquityDotNET/Llvm.NET) LLVM wrapper. Unfortunately this project is currently Windows-only.

**Describe the solution you'd like**
First, Llvm.NET needs to support Linux and MacOS. See [this issue)(https://github.com/UbiquityDotNET/Llvm.NET/issues/193).
Then we need to ensure that the QIR generator works properly on Linux and MacOS.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by crazy4pi314** [comment]
Is there any recent updates on this? Or perhaps any containers that might be helpful in working on QIR on Linux? Thanks!

**Comment by alan-geller** [comment]
I'm working on getting Llvm.NET to build cross-platform. Steady but slow progress.

I'm confident we'll have Llvm.NET ready by the end of the year; I'm not sure whether this will let us merge QIR generation into main before January, though, as there are other integration issues.

I haven't done anything about setting up a container, I'm afraid.

**Comment by bettinaheim** [comment]
Done.

**Comment by crazy4pi314** [comment]
TYSM, this works great! 🥳
