### ISSUE TITLE
Minor QIR fixes to match spec updates

### ISSUE THREAD

**Issue by alan-geller** [microsoft/qsharp-compiler#658]
**Describe the bug**

Recent QIR spec updates should be matched by the QIR generator:

[ ] Validate that exponents for integer and bigint power operators fit in 32 bits
[ ] Validate that range steps are non-zero

**To Reproduce**

N/A

**Expected behavior**

N/A

**Screenshots**

N/A

**System information**

N/A

**Additional context**

N/A

**Comment by bettinaheim** [comment]
Done.
