### ISSUE TITLE
Some non-concretized callables are allowed to be called or given as arguments

### ISSUE THREAD

**Issue by samarsha** [microsoft/qsharp-compiler#662]
**Describe the bug**

The Q# language specification says in [Type Parameterizations](https://github.com/microsoft/qsharp-language/blob/main/Specifications/Language/4_TypeSystem/TypeParameterizations.md):

> A type parametrized callable needs to be concretized before it can be assigned or passed as argument, meaning all type parameters need to be resolved to concrete types.

The compiler doesn't implement this correctly, because the following programs compile:

```qsharp
function Foo<'a>() : Unit { }

@EntryPoint()
function Main() : Unit {
    Foo(); // 'a is not concrete.
}
```

```qsharp
function Undefined<'a>() : 'a {
    fail "Undefined";
}

function Foo<'a>(f : (Unit -> 'a)) : String {
    return "Foo";
}

@EntryPoint()
function Main() : Unit {
    Message(Foo(Undefined)); // 'a is not concrete.
}
```

**Expected behavior**

1. The compiler should forbid the programs above to comply with the language spec; or
2. Since a type system that allows these programs would still be sound, and it may actually be useful to allow this in certain cases, we could consider updating the language spec to loosen the restriction that all type parameters must be concretized.

For an example of why we should allow non-concrete types, consider this program that is not supported currently but would be reasonable to support:

```qsharp
@EntryPoint()
function Main() : Unit {
    let xs = [];
    Message($"{xs}");
}
```

The program should clearly print the string `"[]"`. But the type of `xs` cannot be more specific than `'a[]`, which is not concrete. In the case of empty arrays, the type variable `'a` is not used, though, so it does not actually need to be concrete.

**Additional context**

The example programs cause monomorphization to fail using PR #654:

> System.ArgumentException: Couldn't resolve all type parameters for App.Foo
>    at Microsoft.Quantum.QsCompiler.Transformations.CallGraphWalker.BuildCallGraph.ConcreteCallGraphWalker.<>c__DisplayClass2_0.<GetSpecializationFromRequest>b__1(QsLocalSymbol typeParam) in C:\Users\samarsha\Source\Repos\microsoft\qsharp-compiler\src\QsCompiler\Transformations\CallGraph\ConcreteCallGraphWalker.cs:line 101

This issue is based on this discussion: https://github.com/microsoft/qsharp-compiler/pull/597#discussion_r490666610

**Comment by bettinaheim** [comment]
@samarsha I believe this should be resolved with the switch to the full HM type inference?

**Comment by samarsha** [comment]
Yes, it should be.
