### ISSUE TITLE
Language server regularly throws exceptions that are ignored

### ISSUE THREAD

**Issue by samarsha** [microsoft/qsharp-compiler#669]
**Describe the bug**

The language server can sometimes receive commands that aren't valid for the current server state, due to everything happening asynchronously. These exceptions are expected and in release builds, they are ignored. However, when developing the language server, swallowing all exceptions makes it hard to notice the exceptions that *aren't* supposed to happen, so in debug builds each exception shows up as an error message.

The problem with this is that most of these error messages are benign and should be ignored, which is confusing both to new developers who are setting up a development version of the language server for the first time, and to other developers who have to ignore many expected exceptions during development and may miss important ones.

**To Reproduce**

1. Build the language server in debug mode
2. Set `quantumDevKit.languageServerPath` in the VS Code extension
3. See errors

Examples:

> Microsoft.Quantum.QsCompiler.QsCompilerException: error while running queued task
QsCompilerException: error during scope tracking update
ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'change')
Stack trace: 
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.Utils.GetTextChangedLines(FileContentManager file, TextDocumentContentChangeEvent change) in C:\Users\samarsha\Source\Repos\microsoft\qsharp-compiler\src\QsCompiler\CompilationManager\Utils.cs:line 138

> System.ArgumentException: Position is outside the fragment range (Parameter 'position')
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.CodeCompletion.GetTextIndexFromPosition(CodeFragment fragment, Position position) in C:\Users\samarsha\Source\Repos\microsoft\qsharp-compiler\src\QsCompiler\CompilationManager\EditorSupport\CodeCompletion.cs:line 549

**Expected behavior**

The language server shouldn't rely so heavily on exceptions - exceptions should be for exceptional situations, not situations that happen often during normal use. Most exceptions should probably be converted to `Try*` style methods that return a different value on failure rather than throwing. Alternatively, some specific exceptions could be manually caught and handled, so that unhandled exceptions are reserved for actual programmer errors.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/33814365/95275073-62763880-07fc-11eb-9d66-7316d4db1d4b.png)

**Comment by bettinaheim** [comment]
@samarsha I don't quite follow what cases you had in mind for "situations that happen often during normal use."? The language server is only throwing exceptions in situations that should never happen.

**Comment by samarsha** [comment]
@bettinaheim To summarize our discussion offline, the language server does throw exceptions in situations that happen normally, but are only shown in debug mode. They are caught and ignored in release mode. We are planning to improve the exception handling so that unhandled exceptions don't happen in debug builds, either.
