### ISSUE TITLE
Compile error when an operation name for the entry point matches a namespace

### ISSUE THREAD

**Issue by viktorveis** [microsoft/qsharp-compiler#711]
**To Reproduce**
Create a Q# project with one file: 
```
namespace Test {
    @EntryPoint()
    operation Test() : Unit {
    }
}
```
dotnet build

```
PS C:\src\QSharpPlayground> dotnet build
Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.   

  Determining projects to restore...
  Restored C:\src\QSharpPlayground\QSharpPlayground.csproj (in 734 ms).
  
  ____________________________________________
  
  Q#: Success! (0 errors, 0 warnings) 
  
obj\qsharp\src\Playground.EntryPoint.g.cs(20,58): error CS0117: 'Test' does not contain a definition for 'Test' [C:\src\QSharpPlayground\QSharpPlayground.csproj]
obj\qsharp\src\Playground.EntryPoint.g.cs(23,143): error CS0426: The type name 'Test' does not exist in the type 'Test' [C:\src\QSharpPlayground\QSharpPlayground.csproj]

Build FAILED.
```

**Expected behavior**
Build succeeds.

**System information**

- Version of the NuGet package or extension for which the problem occurs: v0.13.20102604
- Your operating system and .NET Core version: Windows 10, .NET Core 3.1.402

**Additional context**
Removing the `@EntryPoint` attribute fixes the problem.

**Comment by bettinaheim** [comment]
@viktorveis Thanks for reporting! 
Could you please double check the project file that you are using and post it here?
We just recently fixed a couple of C# generation errors, and while the extension updates automatically (depending on your IDE settings), the Sdk in the project file needs to be updated manually for a project to use the new version.

**Comment by viktorveis** [comment]
Yes, this was exactly the problem. The build failed with `<Project Sdk="Microsoft.Quantum.Sdk/0.12.20070124">` in the project file and succeeded after changing it to `<Project Sdk="Microsoft.Quantum.Sdk/0.13.20102604">`.
