### ISSUE TITLE
Missing Microsoft.Quantum.Sdk after installing the Visual Studio QDK extension

### ISSUE THREAD

**Issue by viktorveis** [microsoft/qsharp-compiler#738]
**To Reproduce**
Install the QDK extension for Visual Studio Code - works well
Install the QDK extension for Visual Studio on the same machine
Cannot open and build Q# projects anymore: error MSB4236: The SDK 'Microsoft.Quantum.Sdk' specified could not be found. 

**Expected behavior**
Latest Microsoft.Quantum.Sdk is installed.

**Screenshots**
![image](https://user-images.githubusercontent.com/10914444/98182485-b8510580-1eba-11eb-86cd-f7e0bdd72139.png)

![image](https://user-images.githubusercontent.com/10914444/98182504-cb63d580-1eba-11eb-96aa-411a16747401.png)

**System information**
- OS: Win10
- QDK: v0.13.20102604
- Visual Studio: 16.7.7
- Visual Studio Code: 1.50.1

**Additional context**
Upgrading Visual Studio to the latest version and uninstalling/reinstalling both Visual Studio and Visual Studio code extensions didn't solve the problem.

**Comment by cgranade** [comment]
Is there a version specified for the "Microsoft.Quantum.Sdk" attribute of the `<Project>` element? I'd only expect the .NET Core SDK to look in `c:\Program Files\dotnet\sdk\<version>\Sdks` for Sdk attributes without a version number, since otherwise the .NET Core SDK will query nuget.org.

**Comment by ricardo-espinoza** [comment]
Thanks @cgranade for the quick reply. 

@viktorveis , could you share with us your project? I think Chris' theory makes sense. Normally the binaries should be under your user directory after they get fetched by NuGet, in Windows that would be for example in:
  C:\Users\<user>\.nuget\packages\microsoft.quantum.sdk

I checked that I can't repro the issue with my local installation, but I'd like to try with your project.

**Comment by viktorveis** [comment]
Yes, this was a project file issue. Fixing the project file solved it:
```
<Project Sdk="Microsoft.Quantum.Sdk/0.13.20102604">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
</Project>
```
