### ISSUE TITLE
Code Action - Remove Unreachable Code

### ISSUE THREAD

**Issue by ScottCarda** [microsoft/qsharp-compiler#75]
We want to add a code action that removes unreachable code.

**Comment by ScottCarda** [comment]
The branch I am working on this issue is:
https://github.com/ScottCarda/qsharp-compiler/tree/sccarda/RemoveUnexecutedCode

**Comment by bettinaheim** [comment]
The corresponding PR is https://github.com/microsoft/qsharp-compiler/pull/76.

**Comment by bettinaheim** [comment]
Merged into master with PR #130.
