### ISSUE TITLE
Nested Conditional blocks may be incorrectly lifted

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-compiler#768]
**Describe the bug**

When a conditional includes nested conditionals that modify variables defined outside of the outer conditional scope, the outer conditional may incorrectly be lifted into a generated callable by the ConditionallyControlled rewrite step. See discussion with concrete examples in comments here https://github.com/microsoft/qsharp-compiler/pull/767#discussion_r537819607.

**To Reproduce**

The easiest way to reproduce this is to use [ClassicallyControlledSupportTests.qs](https://github.com/microsoft/qsharp-runtime/blob/main/src/Simulation/Simulators.Tests/TestProjects/HoneywellExe/ClassicallyControlledSupportTests.qs) from the qsharp-runtime repo. Add the following operation to the file:
```qsharp
    operation MutableWithNesting() : Unit {
        mutable x = 0;
        if (x == 0) {
            if (x < 1) {
                set x = 1;
            }
        }
        Message($"{x}");
    }
```
And then recompile the repo. The compilation will succeed and produce generated C# files in the obj/qsharp/src folder. Investigate ClassicallyControlledSupportTests.g.cs, and observe that the outer `if`-statement is lifted into a callabe that is passed the `x` variable as a read-only argument even though the generated body performs an update of that variable. The C# will compile, but the behavior at runtime will be wrong, as the variable `x` will have the value zero after execution instead of the expected value of 1.

**Expected behavior**

Both the inner `if`-statement and the outer one should be recognized as not valid for lifting, so no lifted callables should be generated.

**Comment by bettinaheim** [comment]
@ScottCarda-MS Could you please prioritize looking into this bug; since it leads to incorrect behavior, we should fix it swiftly.

**Comment by bettinaheim** [comment]
@ScottCarda-MS The chases to double check/fix are the following:
1) the case given in the description above is purely classical and should *not* be lifted
2) the following test case that is quantum, should behave correctly:

```qsharp
    operation MutableWithNesting() : Unit {

        use q = Qubit();
        H(q);
        if (true) {
            if (M(q) == Zero) {
                mutable x = 0;
                set x = 1;
            }
        }
        if (M(q) == Zero) {
            mutable x = 0;
            if (x < 1) {
                set x = 1;
            }
        }
        //Message($"{x}");
    }
```
