### ISSUE TITLE
[MacOS] Visual Studio Code extension does not install .NET Core template

### ISSUE THREAD

**Issue by zholobov** [microsoft/qsharp-compiler#77]
**Describe the bug**

No Q# template is installed in .NET Core SDK after Visual Studio Code QDK extension is installed under MacOS.

**To Reproduce**

1. Under macOS Mojave 10.14.6…
1. Install VS Code 1.36.1
2. Install .NET Core SDK 2.2
3. Run VS Code and install extension https://marketplace.visualstudio.com/items?itemName=quantum.quantum-devkit-vscode
4. Note that installation is very quick
5. Go to new terminal window and run `dotnet new console —list`
6. See that there is only default Console Application for C#/F#/VB and no Q#.
7. Run `dotnet new console -lang Q# --output Bell` and see error `'Q#' is not a valid value for -lang (language).`

**Expected behavior**

Expected a Q# project being created using template.

**System information**

- macOS Mojave 10.14.
- .NET Core 2.2.301
- Visual Studio Code 1.36.1
- QDK extension: Name: Microsoft Quantum Development Kit for Visual Studio Code
Id: quantum.quantum-devkit-vscode
Description: Microsoft Quantum Development Kit for Visual Studio Code provides support for developing quantum algorithms in the Q# programming language.
Version: 0.8.19071701
Publisher: Microsoft DevLabs
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=quantum.quantum-devkit-vscode

**Comment by bettinaheim** [comment]
Thanks for reporting! 
Yes, I believe we are indeed not currently packaging these (the corresponding nuget is on https://github.com/microsoft/qsharp-runtime) - we'll take a look into what options there are.

**Comment by bettinaheim** [comment]
See also https://github.com/microsoft/qsharp-compiler/pull/79

**Comment by bettinaheim** [comment]
We've added VS Code commands (Ctl+Shift+P) to install the Q# project templates and create Q# projects. I will close this issue with that. Feel free to open another one if you need anything else.
