### ISSUE TITLE
Monomorphization is not setting the correct parent for specializations

### ISSUE THREAD

**Issue by bettinaheim** [microsoft/qsharp-compiler#773]
The name of the original callable is listed as parent for monomorphized specializations.

**Comment by bettinaheim** [comment]
Fixed in https://github.com/microsoft/qsharp-compiler/pull/774.

**Comment by ScottCarda-MS** [comment]
@bettinaheim Since #744 does not target main, should we wait until this fix is in main to close this issue? Should the fix in #744 be separated out into a different PR targeting main?

**Comment by ScottCarda-MS** [comment]
Merged into Main with #809.
