### ISSUE TITLE
bridge.ll file generated alongside with user's QIR is incomplete and has other issues

### ISSUE THREAD

**Issue by irinayat-MS** [microsoft/qsharp-compiler#775]
Am using feature/qir branch at commit e5ecd6f.

Currently generated bridge.ll file isn't helpful because it doesn't match the runtime:
- names of the types don't match
- names of the functions don't match
- some functionality is missing (e.g. string_concatenate)
- it includes both predefined rt and custom qis methods 
- it might declare signatures, clang cannot produce

In general, I don't see much value in generating the rt part of the bridge for each user's compile. The bridge depends on the implementation of the runtime and doesn't depend on the user's input.

Bridge for qis methods is a different matter. It would be great to generate _both_ bridge_qis.ll file and the corresponding C-header that backs the bridge, to make clear the custom requirements of the user's code.

Also, some of the code in the auto-generated bridge isn't valid:

```
define %Range @__quantum__qis__rangereverse(%Range %arg1) {
entry:
  %0 = call %Range @rangereverse(%Range %arg1)
  ret %Range %0
}

declare %Range @rangereverse(%Range)
```
Runtime doesn't provide `rangereverse` function and there is actually no way to write C-code that Clang would translate into `%Range @rangereverse(%Range)` signature.

**Comment by bettinaheim** [comment]
I'll defer looking at the bridge piece until we have a decently working first version for the basics. I did set the default to not emit the bridge with my latest PR, but left the code in as is for now.

**Comment by bettinaheim** [comment]
I removed the bridge generation and revised the entry point wrapper.
