### ISSUE TITLE
User-Defined Intrinsics Get Duplicated in Syntax Tree

### ISSUE THREAD

**Issue by ScottCarda-MS** [microsoft/qsharp-compiler#779]
**Describe the bug**

A user-defined operation that is made intrinsic will be duplicated in the syntax tree after internal rewrite steps are run.

**To Reproduce**

Compile the following code for a user-defined operation:
```
operation MyIntrinsic(q : Qubit) : Unit is Adj + Ctl {
    body intrinsic;
    adjoint self;
}
```
This `MyIntrinsic` operation will show up twice under the appropriate namespace in the syntax tree after rewrite steps are finished. This can be seen when C# generation is performed, as two identical classes for `MyInternal` will be outputted.

**Expected behavior**

The operation should not be duplicated.

**Comment by bettinaheim** [comment]
I can't reproduce that. Please provide a complete example project on a repo.
