### ISSUE TITLE
Generated QIR doesn't release Results of measurements

### ISSUE THREAD

**Issue by irinayat-MS** [microsoft/qsharp-compiler#780]
Am using feature/qir branch at commit e5ecd6f.

Every `%r = call %Result* @__quantum__qis__mz(%Qubit* %q)` should have a matching `call void __quantum__rt__result_unreference(%Result* %r)` because the runtime might have allocated the results on the heap. Currently, the generated QIR seems to never unreference the results.

**Comment by bettinaheim** [comment]
I believe this should be addressed with the latest changes. I will close this issue once the merge to the feature branch is completed.
