### ISSUE TITLE
Support function and operation types without parentheses

### ISSUE THREAD

**Issue by samarsha** [microsoft/qsharp-compiler#788]
**Is your feature request related to a problem? Please describe.**
The parentheses required around function and operation types is excessive. For example:

```qsharp
function Apply1(f : (Int -> (Int -> Int))) : (Int -> Int) {
    return f(1);
}

function ApplyAdjoint(op : (Qubit => Unit is Adj)) : (Qubit => Unit is Adj) {
    return Adjoint op;
}
```

**Describe the solution you'd like**
I would prefer to write:

```qsharp
function Apply1(f : Int -> Int -> Int) : Int -> Int {
    return f(1);
}

function ApplyAdjoint(op : Qubit => Unit is Adj) : Qubit => Unit is Adj {
    return Adjoint op;
}
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ScottCarda-MS** [comment]
Is there a difference between a function that takes an Int to Int function and returns an Int: `(Int -> Int) -> Int`
and a function that takes an Int and returns and Int to Int function: `Int -> (Int -> Int)`?
If so, such a distinction may be lost if both get represented as `Int -> Int -> Int`

**Comment by samarsha** [comment]
Yes, those types are different. `->` and `=>` are right-associative, so the parentheses implicitly build up right-to-left.

* `a -> b -> c` is `a -> (b -> c)`
* `a -> b -> c -> d` is `a -> (b -> (c -> d))`

This is the most common associativity for arrow types and is used in languages like F# and Haskell to concisely express curried function types (although currying is less common in Q#). To express a function that takes in another function, parentheses are required as in `(Int -> Int) -> Int`.

**Comment by cgranade** [comment]
> This is the most common associativity for arrow types and is used in languages like F# and Haskell to concisely express curried function types (although currying is less common in Q#).

Possibly relevant, but even though currying is uncommon in Q# at the moment, the input ordering convention for Q# APIs is designed to look like currying, in that the most commonly omitted inputs should be the right-most inputs.
