### ISSUE TITLE
Code Action for looping over IndexRange

### ISSUE THREAD

**Issue by bettinaheim** [microsoft/qsharp-compiler#80]
For a for loop over the indices of an array 'arr' 
for (i in 0 .. Length(arr)-1) {
    // code
}
it would be nice if there was a code action (i.e. the little light-bulbs popping up) that a) makes the edit to
for (i in IndexRange(arr)) {
    // code
}
and b) inserts the corresponding open directive for IndexRange if needed. 

**Describe the solution you'd like**
A code action following the same pattern as other code actions should be implemented. 
The relevant code is in [EditorSupport.cs](https://github.com/microsoft/qsharp-compiler/blob/master/src/QsCompiler/CompilationManager/EditorSupport.cs). 

**Additional context**
Please comment on the issue if you would like to pick it up and would like more details/help.

**Comment by ScottCarda** [comment]
I can take a look at this.

**Comment by ScottCarda** [comment]
The branch I am using to work on this issue is:
https://github.com/ScottCarda/qsharp-compiler/commits/sccarda/LoopRangeSimplifyCodeAction

**Comment by ScottCarda** [comment]
The corresponding PR is https://github.com/microsoft/qsharp-compiler/pull/84.

**Comment by bettinaheim** [comment]
Merged into master with PR #130.
