### ISSUE TITLE
Parsing for Q# attributes

### ISSUE THREAD

**Issue by jviszlai** [microsoft/qsharp-compiler#81]
With an end goal of supporting attributes in Q#, the compiler should first be able parse the syntax of attributes and store some information about the identifier and arguments. 
For example:
```
@ExampleAttribute("ExampleArgument")@
operation BitFlip(target : Qubit) : Unit {
    X(target);
}
```

**Comment by bettinaheim** [comment]
@jviszlai Could you please link to the branch where you are working on this?
Let me know how things are going and if you have any questions and/or need help!

**Comment by jviszlai** [comment]
Sure!
Working on this here: https://github.com/jviszlai/qsharp-compiler/tree/features/attributes
I made a PR that addresses most of the parts of this issue I was thinking of, but let me know if there's other parts I should work on: https://github.com/microsoft/qsharp-compiler/pull/82

**Comment by bettinaheim** [comment]
> Sure!
> Working on this here: https://github.com/jviszlai/qsharp-compiler/tree/features/attributes
> I made a PR that addresses most of the parts of this issue I was thinking of, but let me know if there's other parts I should work on: #82

Awesome, thanks! I'll take a look shortly - I will first aggregate all the code action PRs, and then dive into this one.

**Comment by bettinaheim** [comment]
With the PR to master up, I'll close this issue.
