### ISSUE TITLE
QIR: array access counters aren't described in the QIR spec

### ISSUE THREAD

**Issue by irinayat-MS** [microsoft/qsharp-compiler#812]
The QIR code, generated by the Q# compiler at https://github.com/microsoft/qsharp-compiler/commit/d78fef5c0a9f4bccb72256ad9e346cda32a670cd, contains calls to

__quantum__rt__array_add_access
__quantum__rt__array_remove_access

These two functions aren't defined in the QIR spec (https://github.com/microsoft/qsharp-language/blob/main/Specifications/QIR/Data-Types.md)

The specification of `%Array* @__quantum__rt__array_copy(%Array* %array, i1 false)` should be updated to include two arguments.

Also, should the names of the functions be consistent with similar access/user/alias counting methods for tuples?

**Comment by bettinaheim** [comment]
The spec is updated with https://github.com/microsoft/qsharp-language/pull/67. I will hence close the issue here.
