### ISSUE TITLE
QIR: generated QIR assumes different behaviour of qubit_release_array

### ISSUE THREAD

**Issue by irinayat-MS** [microsoft/qsharp-compiler#813]
QIR, generated by the Q# compiler at https://github.com/microsoft/qsharp-compiler/commit/d78fef5c0a9f4bccb72256ad9e346cda32a670cd, might contain the following sequence of calls to the runtime:

```
  call void @__quantum__rt__qubit_release_array(%Array* %qs)
  call void @__quantum__rt__array_unreference(%Array* %qs)
```

However, the QIR spec for `__quantum__rt__qubit_release_array` (https://github.com/microsoft/qsharp-language/blob/main/Specifications/QIR/Quantum-Runtime.md) says "Release an array of qubits." which is most naturally interpreted as releasing the array itself (and, possibly, the contained qubits). If the above is expected semantics for the arrays of qubits, the spec should be updated to clarify that (and probably it would make sense to change the name of the method).

**Comment by bettinaheim** [comment]
The specs are updated with https://github.com/microsoft/qsharp-language/pull/67. I will hence close the issue here.
