### ISSUE TITLE
Unable to compile Quantum demo project

### ISSUE THREAD

**Issue by alfogo** [microsoft/qsharp-compiler#825]
Hi,

I recently installed QDK 0.14.2011120240 to start a new Q# project from scratch.
Unfortunately I am unable to compile it:

![image](https://user-images.githubusercontent.com/8256455/105207199-88bfaa00-5b47-11eb-9256-aa25eed80c10.png)

My .net core sdk versions:

![image](https://user-images.githubusercontent.com/8256455/105207303-a725a580-5b47-11eb-9792-36f656bbcc8b.png)

Looks like same issue #434 ?

Thank you

**Comment by samarsha** [comment]
Hi @alfogo, could you try these steps to give us more detailed log messages:

1. Click on the "Output" tab (next to "Problems")
2. Select "Q# Language Extension" from the drop-down menu on the right side
3. Copy the text from there into this issue

Also, another thing you could try is to run `dotnet build` from the terminal to see if your Q# project builds successfully without the Visual Studio Code extension.

**Comment by alfogo** [comment]
Hi @samarsha ,

This is the output text:

```
[Info  - 13:05:07] workspace folder: c:\Users\xxx\source\repos\Quantum
[Error - 13:05:15] MSBuild error in C:\Program Files\dotnet\sdk\3.1.405\NuGet.targets(128,5): The package is missing the required nuspec file. Path: C:\Users\xxx\.nuget\packages\fsharp.core\4.7.0
[Error - 13:05:15] Failed to restore project 'c:\Users\xxx\source\repos\Quantum\HelloQuantum\HelloQuantum.csproj'.
[Error - 13:05:15] MSBuild error in C:\Program Files\dotnet\sdk\3.1.405\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): Assets file 'c:\Users\xxx\source\repos\Quantum\HelloQuantum\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
[Error - 13:05:15] Failed to resolve assembly references for project 'c:\Users\xxx\source\repos\Quantum\HelloQuantum\HelloQuantum.csproj'.
Discovered Q# project 'c:\Users\xxx\source\repos\Quantum\HelloQuantum\HelloQuantum.csproj'.
Loading project 'c:\Users\xxx\source\repos\Quantum\HelloQuantum\HelloQuantum.csproj'.
Done loading project 'c:\Users\xxx\source\repos\Quantum\HelloQuantum\HelloQuantum.csproj'
```

I tried running dotnet build withouth the VS Code extension and this is what I got:

```
PS C:\Users\xxx\source\repos\Quantum\HelloQuantum> dotnet build
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error NU5037: The package is missing the required nuspec file. Path: C:\Users\xxx\.nuget\packages\fsharp.core\4.7.0 [C:\Users\xxx\source\repos\Quantum\HelloQuantum\HelloQuantum.csproj]

Build FAILED.

C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error NU5037: The package is missing the required nuspec file. Path: C:\Users\xxx\.nuget\packages\fsharp.core\4.7.0 [C:\Users\xxx\source\repos\Quantum\HelloQuantum\HelloQuantum.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.71
PS C:\Users\xxx\source\repos\Quantum\HelloQuantum>
```
Thx

**Comment by samarsha** [comment]
Thanks! That's strange, I haven't seen that error before, and the FSharp.Core package shouldn't actually be needed to compile a Q# project. Could you post your project file (HelloQuantum.csproj) here?

**Comment by alfogo** [comment]
Sure, here it is:

HelloQuantum.csproj
```
<Project Sdk="Microsoft.Quantum.Sdk/0.14.2011120240">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

</Project>
```

**Comment by bettinaheim** [comment]
Since the error is from a package and doesn't seem to have anything to do with the project or Q# in particular, have you tried clearing the nuget cache in case your local package somehow got corrupted? `dotnet nuget locals all --clear` would do that (your local packages will get deleted and will be downloaded again when you build/restore a project that needs them).

**Comment by alfogo** [comment]
Thx @bettinaheim , clearing nuget cache worked out
