### ISSUE TITLE
'Failed to compile program' when attempting to submit job to Azure Quantum Workspace using Azure CLI

### ISSUE THREAD

**Issue by tomaustin700** [microsoft/qsharp-compiler#854]
**Describe the bug**

When attempting to submit a job to Azure Quantum Workspace I'm getting a 'Failed to compile program' error. The program does compile file as I can run dotnet build and it builds successfully. Please see screenshots below.
![image](https://user-images.githubusercontent.com/6324102/106898442-1a085200-66ec-11eb-97d6-2eee49ea3780.png)

![image](https://user-images.githubusercontent.com/6324102/106898492-2ab8c800-66ec-11eb-9341-126837b14656.png)

**To Reproduce**

1. Create an Azure Quantum Workspace
2. Make sure your local Azure CLI can connect to the Workspace
2. Unzip the attached project
3. Attempt to submit it as a job to the workspace. 

[JobTest.zip](https://github.com/microsoft/qsharp-compiler/files/5925952/JobTest.zip)

I'm unsure which target-id I should be using but I've tried them all and I'm still getting the same problem.

**Expected behavior**

When attempting to submit job I receive 'Failed to compile program' even though Visual Studio and dotnet build can compile it successfully.

**System information**

- Visual Studio Quantum Development Kit 0.15.2101.126940
- Visual Studio Enterprise 16.8.4
- Windows 10 Enterprise 20H2, 
- .NET 5.0.102
![image](https://user-images.githubusercontent.com/6324102/106899878-cac32100-66ed-11eb-8861-a84a0ab3a45a.png)

**Comment by bettinaheim** [comment]
@tomaustin700 Thanks for reporting!
We are looking into giving a more actionable message on this one. 

Could it be that your project does not use the IonQ/Honeywell templates? 
If so, then that would mean that the build succeed because in general it is a valid program, but it uses language features that are not supported by the target hardware. You will get IntelliSense and build diagnostics for those things if you use the IonQ/Honeywell templates.

**Comment by tomaustin700** [comment]
Hi @bettinaheim,
My project is pretty simple, it's just the basic hello world example so I don't think it needs the IonQ/Honeywell template however I may be wrong - this is all very new to me. My original message does contain my sample project if you want to take a look at it. My workspace does only have the Microsoft QIO provider so do you think that's the case? Thanks

**Comment by bettinaheim** [comment]
@tomaustin700 Got it - sorry, I did not read carefully enough. Azure Quantum offers both; running quantum inspired optimization algorithms (such as e.g. simulated annealing) and running quantum algorithms on real quantum hardware using Q#. The target id you are using is for quantum inspired optimization (that is a classical solver running on classical hardware). The Q# program you are trying to submit on the other hand is for running on quantum hardware. You can learn more about both in our MS Learn modules. 
[This module](https://docs.microsoft.com/en-us/learn/modules/run-algorithms-quantum-hardware-azure-quantum/), e.g., tells you more about how to run Q# programs on quantum hardware.
[This module](https://docs.microsoft.com/en-us/learn/modules/solve-quantum-inspired-optimization-problems/), e.g., tells you more about solving optimization problems using quantum inspired optimization.
[Here](https://docs.microsoft.com/en-us/learn/browse/?terms=quantum) is the list of MS Learn module that, e.g., also contain content about how to setup your workspace in Azure, and other interesting content.

**Comment by bettinaheim** [comment]
@tomaustin700 I hope this resolved your issue and will close this. Please don't hesitate to reopen it or open a new one if there is more we can help with.
