### ISSUE TITLE
Formatter should update deprecated array syntax to new syntax

### ISSUE THREAD

**Issue by samarsha** [microsoft/qsharp-compiler#863]
The formatter should be able to automatically update the deprecated array syntax, `new T[n]`. For example, `new T[0]` can be replaced with `[]` in most cases. Also, for types with a known default value, e.g. `Int`, then `new Int[n]` can be replaced with `[0, size = n]`.

**Comment by ScottCarda-MS** [comment]
@samarsha should this issue be broken into separate issues for each deprecated syntax to be updated? For example updating the 'using' syntax can be separate from updating the array syntax.

**Comment by samarsha** [comment]
Sure, I updated this issue to be specifically about deprecated array syntax.

**Comment by ScottCarda-MS** [comment]
Closed with #1135
