### ISSUE TITLE
Formatter should compare input source with unparsed tree as a sanity test

### ISSUE THREAD

**Issue by samarsha** [microsoft/qsharp-compiler#867]
As a sanity test to prevent data loss when formatting, the formatter should unparse the CST (without applying any formatting rules) and make sure that it's equal to the original input source code. If it's not, then the formatter shouldn't continue (ideally with an error message asking the user to report a bug).

**Comment by samarsha** [comment]
Hi @yjt98765, you mentioned you were interested in working on this, so I can explain my idea some more.

The type of bug that this is trying to prevent is when there's a silent error in the translation from the parse tree to the syntax tree - so the syntax tree appears to have been constructed successfully, but data may have accidentally been lost or rearranged. For example, maybe the open and close parentheses of an expression accidentally swapped places in the `ExpressionVisitor`.

I think it would be better to stop the formatter with an error message in this case instead of continuing and outputting an incorrect Q# file for the user. So when the `Formatter.format` function is called, before it runs any formatting rules, it could call `printer.Document` and make sure the output matches the original source code exactly, and return an error if it doesn't.

**Comment by yjt98765** [comment]
Hi @samarsha, thank you for the hint. I have initiated a pull request. I think it generally meets the target, but maybe some details need to be further discussed, such as the line-ending matching. I can continue improving it based on your feedback.
