### ISSUE TITLE
QIR generation should suppress C# generation and compilation

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-compiler#869]
When using the upcoming feature for QIR generation (see https://github.com/microsoft/qsharp-compiler/tree/feature/qir), setting `QirGeneration` to true in the project file includes that rewrite step but then still generates C# and tries to compile it, which may or not may not work for the given source + target + rewrite steps.

**Describe the solution you'd like**
Opting into QIR generation should automatically suppress C# generation except for a file with an empty main function, such that C# compilation is effectively a no-op. Additionally, we could output a warning indicating that only QIR was generated until the point where that scenario is fully supported end-to-end.

**Describe alternatives you've considered**
We could also consider finding a way to avoid invoking C# compilation at all, but given that this is in a .csproj that might be more trouble than it is worth.

**Comment by bettinaheim** [comment]
Done with https://github.com/microsoft/qsharp-compiler/issues/869.
