### ISSUE TITLE
Captures created upon lifting into global callables should be minimal

### ISSUE THREAD

**Issue by bettinaheim** [microsoft/qsharp-compiler#903]
Currently, in particular e.g. the classical control transformation builds larger captures than it needs to when lifting blocks into global callables. This should be cleaned up since it is unnecessary and may have a performance impact.

**Comment by bettinaheim** [comment]
This should be addressed once the work for the lambda expressions completes, see also https://github.com/microsoft/qsharp-compiler/issues/1294.

**Comment by ScottCarda-MS** [comment]
This should already be completed and merged into main as part of the lifting refactor done ahead of the work for the lambda lifter.
