### ISSUE TITLE
Possible null reference return in QIR.Emission.IValue.Cached<T>.Load()

### ISSUE THREAD

**Issue by samarsha** [microsoft/qsharp-compiler#904]
`cache` has type `(int, T?)`.

https://github.com/microsoft/qsharp-compiler/blob/a25ab902456a93c0acdcbe81235e9b93606bea30/src/QsCompiler/QirGeneration/QIR/DataStructures.cs#L35-L37

`Load()` has return type `T`.

https://github.com/microsoft/qsharp-compiler/blob/a25ab902456a93c0acdcbe81235e9b93606bea30/src/QsCompiler/QirGeneration/QIR/DataStructures.cs#L60

However, it returns `this.cache.Item2`, which has type `T?`.

https://github.com/microsoft/qsharp-compiler/blob/a25ab902456a93c0acdcbe81235e9b93606bea30/src/QsCompiler/QirGeneration/QIR/DataStructures.cs#L71

This is unsound. The C# compiler doesn't check this for some reason, though.

@bettinaheim @swernli

**Comment by bettinaheim** [comment]
@samarsha I am not sure I understand you correctly; I believe the C# compiler is correct. We have the following code:

```
            public bool IsCached =>
                this.cache.Item2 != null &&
                (this.store == null || !this.sharedState.IsWithinLoop || this.cache.Item1 == this.sharedState.CurrentBranch) &&
                this.sharedState.IsOpenBranch(this.cache.Item1);

            /// <summary>
            /// Returns the cached value stored or loads it if necessary.
            /// </summary>
            public T Load()
            {
                // We need to force that mutable variables that are set within the loop are reloaded
                // when they are used instead of accessing the cached version.
                // We could be smarter and only reload them if they are indeed updated as part of the loop.
                if (!this.IsCached)
                {
                    var loaded = this.load();
                    this.cache = (this.sharedState.CurrentBranch, loaded);
                }

                return this.cache.Item2;
            }
```
Load checks is IsCached, which in particular is false when cache.Item2 is null. If IsCached is null, then the cache is set to value returned by loaded, which is `T`, not `T?`. If you comment out the content of the IsCached block, you will see the C# compiler starting to complain.

**Comment by bettinaheim** [comment]
@samarsha I see what you mean by the C# compiler not detecting potential issues here; if you set `public bool IsCached => true;` in all cases, then the compiler is still happy with it even though it shouldn't. While this is potentially something to file against the C# compiler, I believe in our case the code is safe and Load indeed never returns null.

**Comment by samarsha** [comment]
In terms of the type system, the definition of `IsCached` isn't relevant. The fact that `IsCached == true` implies `this.cache.Item2 != null` isn't (and can't be, as far as I know) captured in the type of `IsCached`.

Rider's nullable analysis is better than Roslyn, which is why I noticed this, since Rider displays this as an error. Maybe it'd be better in this case to use `return this.cache.Item2!` to indicate that this return value is unsafe? That also silences the error in Rider.

**Comment by bettinaheim** [comment]
I'd still disagree about the unsafe - clearly a good enough inference could know that the value at this point can never be null. I am happy to add the exclamation mark, but if you look at how nullables behave, then you will see that in plenty of places if you have something like 
```
T? value = something; // may be null
if (value == null)
{
    // return or throw
}
// value here is inferred not to be null
```

you will see that inference in fact determines that the value is not null. It would be pretty awkward to work with nullables if it didn't. I'd argue that a) there is a case that the C# compiler doesn't cover regarding its null check (they are not covering everything with perfect accuracy, which is the trade off for being able to retroactively introduce these kinds of checks), and b) the Rider inference is not good enough here (arguable the inference is correct if you were to postulate that nullability is a property of the type system, but it really isn't in the way you would expect it from languages that make that distinction from the get go at the type system level).

**Comment by samarsha** [comment]
> I'd still disagree about the unsafe - clearly a good enough inference could know that the value at this point can never be null.

Sure, full-problem analysis could statically determine that this is safe. That's not what nullable reference types are, though. They are type-level annotations and any null checking should be based on those types and associated attributes, not on the definition of a property. What if `IsCached` was in an interface and its implementation was unknown until runtime?

> you will see that inference in fact determines that the value is not null. It would be pretty awkward to work with nullables if it didn't.

Yes, that's flow typing. It doesn't extend to null checks that occur in other methods. Flow typing itself relies on type-level annotations to propagate nullable information.

> the Rider inference is not good enough here

I think Rider is correct here. By design, it can't infer this information. As you mentioned, Roslyn is only allowing this code because of a bug - it's not checking the contents of `IsCached` either.

**Comment by bettinaheim** [comment]
"Flow typing itself relies on type-level annotations to propagate nullable information" That has been one of the most cumbersome restrictions working with nullables to me. In any case, I added the exclamation mark and a comment to https://github.com/microsoft/qsharp-compiler/pull/906.
