### ISSUE TITLE
Unclear how to build qsharp-compiler from sources.

### ISSUE THREAD

**Issue by kuzminrobin** [microsoft/qsharp-compiler#910]
From the page https://github.com/microsoft/qsharp-compiler/ it is not clear what to do after the `bootstrap.ps1` step in order to build from sources the QsCompiler (not the extension for VS or VSCode).
The `README.md` likely needs to mention 
`QsCompiler.sln` 
and the scripts that are used by the CI builds.

Also what are the instructions to build for Linux and Mac?

**Comment by bettinaheim** [comment]
Started a draft here: https://github.com/microsoft/qsharp-compiler/pull/911.
