### ISSUE TITLE
QSC reruns in pipeline even when it shouldn't

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-compiler#932]
In the e2e build pipelines, the "Test All" step for samples should do barely any building because all of the projects were already built by the "Build All" step. But instead it appears to rerun at least some of the builds of Q# contents (see [logs of this qsharp-compiler.e2e pipeline](https://dev.azure.com/ms-quantum-public/Microsoft%20Quantum%20(public)/_build/results?buildId=24886&view=logs&j=a2216479-a128-57f4-3cb4-920ada5b8bb8&t=a7a52cb8-baeb-5488-7f08-18538eb1c327&l=327)). Any time we see `Q#: Success!` it indicates that qsc was run, which tells us that we are recompiling code that shoudn't need to be recompiled. While we could work around this in the pipeline by specifying `--no-build` on the `dotnet test` invocation, we'd just be dodging what could be a potential compiler bug.

We should investigate with both the pipeline and some smaller local projects why qsc seems to be getting invoked even when the build was already completed.

**Comment by swernli** [comment]
Of note, I can't seem to get this to repo outside of the pipeline. In my local environment, qsc correctly only runs when the .qs files of the project have changed, as expected. So perhaps this is somehow a side effect of the package reference to project reference redirect the e2e builds utilize?

**Comment by bettinaheim** [comment]
Off the top of my head, I don't remember how the build pipeline is set up, but here are the conditions against which the incremental build checks: https://github.com/microsoft/qsharp-compiler/blob/f7c51ab72319487d607f5a9f7bf6b08e9cd86d2f/src/QuantumSdk/Sdk/Sdk.targets#L131

**Comment by swernli** [comment]
With Bettina's help I think we have this narrowed down to a cause! At the very least, we have evidence now on how to repro locally and it fixes it locally. PR to be linked soon; hopefully this works better in the e2e builds as well. If not, I'll keep this open to track that specific issue.

**Comment by swernli** [comment]
The change in #1041 seems to have had the desired affect and e2e build times are getting reduced :).
