### ISSUE TITLE
Docs gen issue in AssertMeasurement[Probability](): The type of `result` param is `invalid`

### ISSUE THREAD

**Issue by kuzminrobin** [microsoft/qsharp-compiler#949]
It is confusing that the type of the `result` parameter is `invalid` [here](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.diagnostics.assertmeasurement#result--invalid) and [here](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.diagnostics.assertmeasurementprobability#result--invalid). 
Documentation rendering issue?

---
Same for [Measure() `Output`](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.intrinsic.measure#output--invalid) (and all entities of type `Result`?).

**Comment by bettinaheim** [comment]
@cgranade Are you looking into this, or making sure it gets triaged?

**Comment by cgranade** [comment]
I haven't had the chance to look into it yet, sorry, but wanted to at least make sure it was triaged in the meantime.

**Comment by cgranade** [comment]
My initial thought is that it comes down to the `ToMarkdownLink` extension method at https://github.com/microsoft/qsharp-compiler/blob/1fd018a6490ca7c0aa42c2f67d7429c85362b187/src/Documentation/DocumentationGenerator/Extensions.cs#L285. It should be an easier fix than I was afraid of, so I'll make a PR for it shortly.

**Comment by bettinaheim** [comment]
@cgranade Thanks! No rush, I just wanted to make sure someone has an eye on it.

**Comment by cgranade** [comment]
Makes sense! In investigating the fix seems to be pretty straightforward, so I just went on and opened the PR.
