### ISSUE TITLE
Some code actions are not offered in VS Code on Linux

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp-compiler#967]
**Describe the bug**

VS Code extension on Linux doesn't offer at least some of the code actions that are offered in Visual Studio on Windows. (I haven't had a chance to check VS Code on Windows, sorry.)

**To Reproduce**

I tried the code action which opens namespace for a library operation. Typing in the operation name gives an error, with "No quick fixes available".

**Screenshots**

![VSCode-code-actions-na](https://user-images.githubusercontent.com/10113024/114605888-683b5380-9c4f-11eb-9d21-b9ac209d1592.png)

**Expected behavior**

I expected a code action ("quick fix"?) to appear offering to open namespace.

**System information**

- Version of QDK extension: 0.15.2103133969
- Linux, .NET Core 3.1.407
- VS Code 1.54.3

**Comment by bettinaheim** [comment]
@ricardo-espinoza Could you make sure this issue gets triaged and processed as appropriate? Thanks!

**Comment by ricardo-espinoza** [comment]
Investigating. @tcNickolas , did you notice this as a regression or have you never used that quick action in VS Code for Linux that you can recall?

**Comment by tcNickolas** [comment]
I haven't used QDK on Linux for a couple of years, so I cannot really say - it's quite possible my first use was pre-code actions :-)

**Comment by ricardo-espinoza** [comment]
This isn't a Linux specific problem. The issue here is that code actions are not specified with Kind = QuickFix, so they are available but are not shown as quick fix options in the UI referenced in the UI above.

This is tracked by bug #1268
