### ISSUE TITLE
[QIR] Array Concatenation is missing ref count increase

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-compiler#970]
When QIR emission handles array concatenation, a new array is created that includes the items from the two source arrays. However, this does not result in a ref count increase of the items in the newly combined array. As a result, one or both of the source arrays used in the concatenation goes out of scope while the combined array is still in use some of the items may be freed, resulting in a crash the next time they are accessed from the combined array.

I believe this code could result in the issue, but I haven't had the chance to confirm yet:
```qsharp
function MakeList() : (Int, Int)[] {
    let a = (1, 2);
    let b = (3, 4);
    return [a] + [b];
}

function UseList() : (Int, Int) {
    let myList = MakeList();
    return myList[0];
}
```

**Comment by swernli** [comment]
I was able to confirm that the above Q# does reproduce the issue.

**Comment by bettinaheim** [comment]
Reopening due to https://github.com/microsoft/qsharp-compiler/pull/989.
