### ISSUE TITLE
[QIR] Repeated invocation of partial application of operation using UDT fails

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-compiler#973]
I'm not exactly sure what is going on for this one, but I was at least able to isolate it to a relatively small example code:
```qsharp
namespace Microsoft.Quantum.Qir.Emission {
    open Microsoft.Quantum.Intrinsic;
    open Microsoft.Quantum.Canon;
    open Microsoft.Quantum.Synthesis;

    @EntryPoint()
    operation EntryPoint() : Unit {
        let array = [Identity1C(), Identity1C()];
        use q = Qubit();
        // ApplyToEach(Apply1C(_, q), array);
        for g in array {
            Apply1C(g, q);
        }
    }

}
```
The commented out line and the for-loop should be functionally equivalent, but the loop succeeds and the `ApplyToEach` version will crash. My best guess is that this is something to do with tuple passing when preparing the capture for the partial application, because the debugger breaks in on an Access Violation due to null dereference somewhere in the generated QIR with `QirCallable::Invoke` on the stack. Looking inside of `QirCallable::Invoke` I can't tell what callable is being invoked but I can see that the capture associated with it is null and the args are empty.

**Comment by bettinaheim** [comment]
The issue is one indirection too many: The partial application for some reason expects the argtuple to be a tuple with a single item where the single item is a tuple of four items. When it is invoked, however, it gets simply a tuple with four items, resulting in undefined behavior. I'm looking into it.
