### ISSUE TITLE
IR specification

### ISSUE THREAD

**Issue by bettinaheim** [microsoft/qsharp-compiler#98]
We need to formally define an IR format to compile into to facilitate a broader use. The expectation is that similarly to the compiler extensibility for transformations on top of the library format (see SyntaxTree.fs) today, it should be possible to plug into the compiler at this stage as well.

**Comment by anfelor** [comment]
Would that format be the output of the Q# compiler and the input of the Q# simulator?

**Comment by bettinaheim** [comment]
@anfelor 
Yes, that would be the idea. We have some ideas we are working on, and hopefully we should be able to share them more broadly within the next six months to a year. We have a somewhat longer time line here due to the impact on hardware providers. I will file an issue to actually have something like a roadmap on this repo to give better visibility into our process, though it might take a bit of time since we have to prioritize some of the immediate development work. Thanks for your interest and understanding! Let me know if you have concrete questions or ideas!

**Comment by samarsha** [comment]
@bettinaheim I think this is now resolved by the QIR specification on qsharp-language, but please re-open if there is still remaining work that needs to be done here.

https://github.com/microsoft/qsharp-language/tree/main/Specifications/QIR
